### ISSUE TITLE
Ethics Training Certification

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/Forms#341]
It's an online course employees have to take on the State's website. They get a certificate at the end they have to send to compliance. 

PDF: 
https://drive.google.com/open?id=0B-1g6uX3Hb0HSE1WZWZxeUlpZ2c

Contact:
ann.braga@boston.gov

**Comment by reillyzlab** [comment]
@joshuagee think probably related to this: https://hub.boston.gov/conflict-interest-law-summary

But, definitely a better way to organize that info which looks like you're doing

**Comment by joshuagee** [comment]
I am JUST about to send you another email that includes this.

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/Xic05J

**Comment by joshuagee** [comment]
https://hub.boston.gov/ethics-online-training-report-form

**Comment by joshuagee** [comment]
Also did significant design work on overhauling the paper version of this form

[ethics_certification_form6.pdf](https://github.com/CityOfBoston/Forms/files/821932/ethics_certification_form6.pdf)
