### ISSUE TITLE
Affordable Housing Lottery Application for 200 Brookline Ave

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/Forms#401]
contact: alexis.buckley@boston.gov
Child of #376

**Comment by joshuagee** [comment]
We need a rental application for the following:

Distribution Period: Oct 19th to Oct 31st

Development name: 200 Brookline Ave
Development Address: 200 Brookline Avenue, Boston MA 02215
Deadline to submit the application: Wednesday, November 1st, 2017
Address to mail application: c/o 200 Brookline Avenue, 257 Hillside Avenue, Needham, MA 02494

Developer: Leslie Cohen
Email:lcohen@samuelsre.com

Agent: Mbom DeAndrade
Email: seb.housing@gmail.com
Telephone: 617-782-2300 x206

There are 10 studio, 21 1br, 8 2br, 2 3br for lease 

Please Remove:

Section 2:
vision impairment from disabilities
Section4:
homelessness
artist questions
first-time homebuyer
elderly

**Comment by joshuagee** [comment]
Paper application [200 Brookline Ave_Paper Application.pdf](https://github.com/CityOfBoston/Forms/files/1376411/200.Brookline.Ave_Paper.Application.pdf)

**Comment by joshuagee** [comment]
> There are 10 studio, 21 1br, 8 2br, 2 3br for lease

Options should be studio, 1br, 2 br, and 3 br?

**Comment by Danchen-Xu** [comment]
@joshuagee Hi Josh! We need a rental application for the following:

Distribution Period: Oct 19th to Oct 31st

Development name: 200 Brookline Ave
Development Address: 200 Brookline Avenue, Boston MA 02215
Deadline to submit the application: Wednesday, November 1st, 2017
Address to mail application: c/o 200 Brookline Avenue, 257 Hillside Avenue, Needham, MA 02494

Developer: Leslie Cohen
Email:lcohen@samuelsre.com

Agent: Mbom DeAndrade
Email: seb.housing@gmail.com
Telephone: 617-782-2300 x206

In Section 2, under bedroom size preferences, please keep Studio, 1 BR, 2 BR, and 3BR

In section 3, please keep the Boston Residency Preference.

We will need this by next Wednesday. 

Please share the access to the spreadsheet with marketing agent Brian Engler at brian@s-e-b.com

Thank you!

**Comment by Danchen-Xu** [comment]
Here is the paper version of the application.[200 Brookline Ave_Paper Application.pdf](https://github.com/CityOfBoston/Forms/files/1376853/200.Brookline.Ave_Paper.Application.pdf)

**Comment by Danchen-Xu** [comment]
Updated application with November 7th as application submission deadline
[200 Brookline Ave_Paper Application.pdf](https://github.com/CityOfBoston/Forms/files/1388313/200.Brookline.Ave_Paper.Application.pdf)

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/e49uddjn2ip2

**Comment by joshuagee** [comment]
https://www.boston.gov/200-brookline-ave-affordable-housing-lottery-application
