### ISSUE TITLE
Affordable Housing Lottery Application for Siena Condominium

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#402]
Contact person: Alexis Buckley, alexis.buckley@boston.gov, Danchen Xu, danchen.xu@boston.gov
Child of #376 

@joshuagee Hi Josh! 

We need a sale application for the following:

Distribution Period: October 19th to October 31st

Development name: Siena Condominium
Development Address: 40 Traveler Street, Boston, MA 02118
Deadline to submit the application: Tuesday, November 7th
Address to mail application: c/o Siena Condominium, 257 Hillside Avenue, Needham, MA 02494

Developer: Doug Straus
Email: dstraus@natdev.com

Agent: Mbom DeAndrade
Email: seb.housing@gmail.com
Telephone: 617-782-2300 x206

- [x] Under Section 2 of the application, please keep only Studio.

- [x] There are no income restricted units built out for persons with disabilities in this development, so please remove disability information questions.

- [x] Under Section 3, please remove the housing assistance information questions.

- [x] Under Section 4, please keep the First Time Homebuyer and Boston Residency questions.

We will need this by next Wednesday.

Please also share the spreadsheet with marketing agent Brian Engler at brian@s-e-b.com

Thank you!

**Comment by Danchen-Xu** [comment]
Here is the paper application. Thank you! [SIENA Condominium_ Paper Application.pdf](https://github.com/CityOfBoston/Forms/files/1376884/SIENA.Condominium_.Paper.Application.pdf)

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/1l2jc0rgsxrz

**Comment by joshuagee** [comment]
https://www.boston.gov/siena-condominium-affordable-housing-lottery-application
