### ISSUE TITLE
Affordable Housing Lottery Application for Pierce Condominium

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#403]
Contact person: Alexis Buckley, alexis.buckley@boston.gov, Danchen Xu, danchen.xu@boston.gov
Child of #376

**Comment by Danchen-Xu** [comment]
Hi Josh, 

We need a sale application for the following:

Distribution Period: Oct 19th to Oct 31st

Development name: Pierce Boston Condominium
Development Address: 188 Brookline Avenue, Boston, MA 02215
Deadline to submit the application: Tuesday, November 7th 
Address to mail application: c/o Pierce Boston Condominium, 257 Hillside Ave, Needham, MA 02494

Developer: Leslie Cohen
Email: lcohen@samuelsre.com

Agent: Mbom DeAndrade
Email: seb.housing@gmail.com
Telephone: 617-782-2300 x206

For the Application Form, please make the following edits:

- Under Section 2, please keep only 1br
- Under Section 2, please remove the disability information questions, as there is no income-restricted unit built for persons with disabilities.

- Under Section 3, please remove the Housing Assistance Information

- Under Section 4, please keep only these two (2) preferences: First Time Homebuyer, Boston Residency

We will need this by next Wednesday, October 18th.

Please also share the spreadsheet with Brian Engler at brian@s-e-b.com

Thank you!

**Comment by Danchen-Xu** [comment]
Here is the paper application for Pierce Boston Condominium. Thank you![Pierce, The_Paper Application.pdf](https://github.com/CityOfBoston/Forms/files/1376909/Pierce.The_Paper.Application.pdf)

**Comment by Danchen-Xu** [comment]
Updated paper application for Pierce Boston Condo 
[Pierce, The_Paper Application.pdf](https://github.com/CityOfBoston/Forms/files/1388303/Pierce.The_Paper.Application.pdf)

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/wmphwscquhh8

**Comment by joshuagee** [comment]
https://www.boston.gov/pierce-condominium-affordable-housing-lottery-application

**Comment by alexisbuckley** [comment]
@joshuagee  Hi Josh, Brian Engler forwarded an email stating that applicants for the Pierce are not receiving the confirmation email with their application.  Can you please make sure this is set up? Thanks!

**Comment by joshuagee** [comment]
@alexisbuckley It's turned on, so they should.
