### ISSUE TITLE
Affordable Housing Lottery Application for the Harlo

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#404]
Contact person: Alexis Buckley, alexis.buckley@boston.gov, Danchen Xu, danchen.xu@boston.gov
Child of #376

**Comment by Danchen-Xu** [comment]
Hi Josh, 

We need a rental application for the following:

Distribution Period: Oct 19th to Oct 31st

Development name: The Harlo
Development Address: 1350 Boylston St, Boston, MA 02115
Deadline to submit the application: Tuesday, November 7th, 2017
Address to mail application: c/o the Harlo, 257 Hillside Ave, Needham, MA 02494

Developer: Mark McGowan
Email: Mark.McGowan@skanska.com

Agent: Mbom DeAndrade
Email: seb.housing@gmail.com
Telephone: 617-782-2300 x206

For the Application Form editing, please make the following changes:
- [ ]  Under Section 2, please only keep Studio, 1 Bedroom, and 2 Bedroom for bedroom size preference
- [ ]  Under Section 2, please only keep mobility impairment for disability information question

- [ ] Under Section 4, please only keep Boston Residency Question

We will need this by next Wednesday.

Please also share the spreadsheet with marketing agent Brian Engler at brian@s-e-b.com

Thank you!

**Comment by Danchen-Xu** [comment]
Here is the paper application 
[Harlo, the_paper application.pdf](https://github.com/CityOfBoston/Forms/files/1376933/Harlo.the_paper.application.pdf)

**Comment by Danchen-Xu** [comment]
Updated application with November 7th as the application submission deadline 
[Harlo, the_paper application.pdf](https://github.com/CityOfBoston/Forms/files/1388310/Harlo.the_paper.application.pdf)

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/w7nsvvt6jjmj

**Comment by joshuagee** [comment]
https://www.boston.gov/harlo-1350-boylston-st-affordable-housing-lottery-application
