### ISSUE TITLE
Affordable Housing Lottery Application for 9 Williams Street 

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#405]
Contact person: Alexis Buckley, alexis.buckley@boston.gov, Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Friday

**Comment by Danchen-Xu** [comment]
Hi Josh, 

We need a RENTAL/SALE application for the following:

Distribution Period:

Development name: 9 Williams Street Rental Housing 
Development Address: 9 Williams Street, Roxbury, MA 02119
Deadline to submit the application: November 10th, 2017
Address to mail application: 207 Dudley Street Roxbury, MA 02119

Developer: Russell Tanner 
Email: rtanner@madison-park.org

Agent: Brian Kean
Email: bkean@winnco.com
Telephone:617-426-1175

For the Application Edition, Please make the following changes:

- [ ] sections2 - bedroom size preferences; please only keep 1br, 2br, and 3br

- [ ] section2 - disability information: please only keep mobility impairment

- [ ] Section 4 - preferences - please only keep Boston Residency

We will need this before the end of this week. 

Please also share the access to the spreadsheet with marketing agent Brian Kean at bkean@winnco.com

Thank you so much!

**Comment by Danchen-Xu** [comment]
Here is the paper application. Thank you! [2101 Washington Street _ Paper Application.pdf](https://github.com/CityOfBoston/Forms/files/1377294/2101.Washington.Street._.Paper.Application.pdf)

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/ubljdazbgro2

**Comment by jduffy2001** [comment]
Boston.gov link:

https://www.boston.gov/9-williams-street-affordable-housing-lottery-application

**Comment by joshuagee** [comment]
Please change the name of the agent contact from Brian Keane to    Margarita Ballester, 9williams@winnco.com 617/445-8338
The fields that normally pop up when one ticks a box for household member 2, household member 3, etc. don't pop up here. There are important fields needed to confirm applications with shared addresses aren't comprised of the same household members (duplicates)
Is it possible to make the link to the income calculation sheet live so people don't have to copy and paste? 
It looks like a similar issue w/ household members and corresponding boxes happened w/ income and assets, too.  The fields for each category under both income and assets, when checked, don't generate a corresponding box in which applicants would fill in the necessary details.
The details about Boston Residency Preferences, the list of required proof of residency docs and the note that if they don't have the docs at the time of certification they'll be out of the lottery are missing. 
The list of languages one may have needed help w/ is missing.

**Comment by Danchen-Xu** [comment]
@joshuagee Please share the access of the spreadsheet with

- [ ] Genesa Patten at gpatten@winnco.com
and
- [ ] Margarita Ballester at mballester@winnco.com'

Thank you!

**Comment by Danchen-Xu** [comment]
@joshuagee Hi Josh,

We just got the message from the marketing agency that they want to change the contact person for applications to Nick Bergdoll. I'm sorry.

Here are Nick Bergdoll's contact details:
Tel.: (617) 879-1620
Email: nbergdoll@winnco.com

Meanwhile, here is the updated paper application with Mr. Bergdoll's contact info: 
[2101 Washington Street _ Paper Application_Edited 101817.pdf](https://github.com/CityOfBoston/Forms/files/1396138/2101.Washington.Street._.Paper.Application_Edited.101817.pdf)


Please update both the 

- [ ] online application

- [ ] paper application for download

Thank you profusely!

**Comment by joshuagee** [comment]
Done. You migth need to hit refresh to see it.
