### ISSUE TITLE
Affordable Housing Lottery Application for 170 West Broadway Codominium

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#406]
Contact person: Alexis Buckley, alexis.buckley@boston.gov, Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Friday, October 27th

**Comment by Danchen-Xu** [comment]
Hi Josh, 

We need a sale application for the following:

Distribution Period: October 28th, 2017 to November 6th, 2017

Development name: 170 Est Broadway Codominiums
Development Address: 170 West Broadway, South Boston, MA 02127
Deadline to submit the application: November 13th, 2017
Address to mail application: c/o 170 West Broadway, 273 "D" Street, South Boston, MA 02127

Developer: Edward Doherty
Email: emmarealty@smn.com

Agent: Michelle Zenga
Email: 170westbroadway@sbndc.org
Telephone: 617-268-9610

For Application Form editing, please make the following changes:

- [ ] section2-bedroom size: please only keep 1br and 2br

- [ ] section2-please remove the disability information questions, as there is no income restricted units built out for persons with disabilities in this development

- [ ] section3- please remove questions in regard to Housing Assistance, as this is a homeownership project

- [ ] section 4 - please only keep First Time Home Buyer and Boston Residency Preferences

We will need this by October 27th.

Please also share the spreadsheet with marketing agent Michelle Zenga at michelle.zenga@sbndc.org

thank you!

**Comment by Danchen-Xu** [comment]
Here is the paper application. 
[Paper Application_170 West Broadway Condominiums.pdf](https://github.com/CityOfBoston/Forms/files/1377323/Paper.Application_170.West.Broadway.Condominiums.pdf)

**Comment by alexisbuckley** [comment]
@josh

**Comment by alexisbuckley** [comment]
sorry josh, not used to github yet. i see that 170 W. Broadway is closed and I've combed through emails looking for the link to the online application but cannot find find it.

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/k4h48qkek5k9

**Comment by joshuagee** [comment]
https://www.boston.gov/170-west-broadway-affordable-housing-lottery-application
