### ISSUE TITLE
Affordable Housing Lottery Application for 275 Old Colony Avenue

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#407]
Contact person: Alexis Buckley, alexis.buckley@boston.gov, Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by October 13th

**Comment by Danchen-Xu** [comment]
Hi Josh, 

We need a sale application for the following:

Distribution Period: October 14th to October 23rd

Development name: 275 Old Colony Avenue Condominium
Development Address: 275 Old Colony Avenue, South Boston, MA 02127
Deadline to submit the application: October 30th, 2017
Address to mail application:c/o 275 Old Colony, 273 "D" Street - South Boston, MA 02127

Developer: Stuart Mullally
Telephone: 617-233-4098 

Agent: Michelle Zenga
Email: 275oldcolonyave@sbndc.org
Telephone: 617-268-9610

For the application form editing, please make the following changes:

- [ ] section2-bedroom size preference: please only keep 2 bedroom

- [ ] section2-disability information question: please remove, as there is no income-restricted unit built for persons with disabilities in this development

- [ ] section3-please remove the housing assistance question, as this is a homeownership project

- [ ] Section 4- please only keep the First Time Homebuyer and Boston Residency Preferences 

We will need this by October 13th.

Please also share the access to the spreadsheet with marketing agent Michelle Zenga at michelle.zenga@sbndc.org

Thank you!

**Comment by Danchen-Xu** [comment]
Here is the copy of the paper application. [275 Old Colony Ave Condominiums - Paper Application.pdf](https://github.com/CityOfBoston/Forms/files/1377344/275.Old.Colony.Ave.Condominiums.-.Paper.Application.pdf)

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/4fyhtnslqy97

**Comment by jduffy2001** [comment]
Drupal link:

https://www.boston.gov/275-old-colony-avenue-affordable-housing-lottery-application
