### ISSUE TITLE
Affordable Housing Lottery Application - 5-9 Woodworth Street

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#408]
Contact person: Alexis Buckley, alexis.buckley@boston.gov, Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by October 15th

**Comment by Danchen-Xu** [comment]
Hi Josh,

We need a sale application for the following:

Distribution Period: October 16th to October 25th

Development name: 5-9 Woodworth Street
Development Address: 5-9 Woodworth Street, Boston, MA 02127
Deadline to submit the application: October 30th, 2017
Address to mail application:c/o 275 Old Colony, 273 "D" Street - South Boston, MA 02122

Developer: Jay Bisognano
Telephone: 978-490-5278


Agent: John Costello
Email: jcostello@maloneyproperties.com
Telephone: 617-209-5250

For the application form editing, please make the following changes:

- [ ]  section2-bedroom size preference: please only keep 2 bedroom

- [ ]  section2-disability information question: please remove, as there is no income-restricted unit built for persons with disabilities in this development

- [ ]  Section 4- please only keep the Boston Residency Preference

We will need this by October 15th.

Please also share the access to the spreadsheet with marketing agent John Costello at jcostello@maloneyproperties.com 

Thank you.

**Comment by Danchen-Xu** [comment]
Here is the paper version of the application
[5-9 Woodworth Street_Paper Application.pdf](https://github.com/CityOfBoston/Forms/files/1380400/5-9.Woodworth.Street_Paper.Application.pdf)

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/ha550qtrlr4p

**Comment by jduffy2001** [comment]
Here's the page in Drupal:

https://www.boston.gov/5-9-woodworth-street-affordable-housing-lottery-application

**Comment by joshuagee** [comment]
the contact number for the agent listed on the website should be 617-209-5403
Deadline to return listed on the website is 11/1/17 (not 10/30)The address to return is 27 Mica Lane, Wellesley, MA 02481 (the website has 275 Old Colony in S. Boston)
The email address on the website is woodworth@maloneyproperties.com
there fields that normally pop up when one ticks a box for household member 2, household member 3, etc. don't pop up here. There are important fields needed to confirm applications with shared addresses aren't comprised of the same household members (duplicates)
Is it possible to make the link to the income calculation sheet live so people don't have to copy and paste? 
It looks like a similar issue w/ household members and corresponding boxes happened w/ income and assets, too.  The fields for each category under both income and assets, when checked, don't generate a corresponding box in which applicants would fill in the necessary details.
The details about Boston Residency Preferences, the list of required proof of residency docs and the note that if they don't have the docs at the time of certification they'll be out of the lottery are missing. 
The list of languages one may have needed help w/ is missing.
