### ISSUE TITLE
Compliance I form missing 

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#410]
Hi Josh,

The development named the Harlo was submitted by the lottery agent and is in the spreadsheet populated from the Seamlessdoc. However, the submitted form was not in the project folder. Can you fix?

Thank you!

Danchen

**Comment by joshuagee** [comment]
@Danchen-Xu Submissions appear to be flowing normally.

**Comment by Danchen-Xu** [comment]
@joshuagee Can we find the missing document? The submission form for the Harlo is missing from Compliance I folder in Google Drive.

**Comment by joshuagee** [comment]
Realizing this isn't a form. Closing and moving to email.
