### ISSUE TITLE
Affordable Housing Application for 50 Liberty

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#415]
Hi Josh, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Friday, 12/1/17

We need a SALE application for the following:

Distribution Period: December 4, 2017 - December 15, 2017

Development name: 50 Liberty 
Development Address: 50 Liberty Drive, Boston, MA 02210 
Deadline to submit the application: December 22, 2017
Address to mail application: c/o 50 Liberty, 27 Mica Lane, Wellesley, MA 02481

Developer: Myrna Putziger
Email: mputziger@falloncompany.com

Agent: John Costello
Email: 50liberty@maloneyproperties.com
Telephone: 781-992-5305

Please Remove: 

Section 2:

- [x] Please remove studio from bedroom sizes
- [x] Please remove the disability questions, because there is no unit built out for persons with disabilities in this development 

Section 3:

- [x] please remove the housing assistance question, because this is a homeownership project

Section 4:

- [x] Please only keep first time home buyer question and Boston residence question. 

 
I have also attached the paper application. 

We will need the application by Friday, 12/1/17

Please also share the spreadsheet with jcostello@maloneyproperties.com

Thank you,

**Comment by Danchen-Xu** [comment]
[50 Liberty Income Restricted Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/1492613/50.Liberty.Income.Restricted.Lottery.Application.pdf)

**Comment by joshuagee** [comment]
@Danchen-Xu For bedroom sizes. The default template goes from studio to 6 BR. Please be clear which to remove. I asked if we should use fewer default sizes and was told no. So in the meantime you'll need to tell me to remove those each time. Thanks!

**Comment by joshuagee** [comment]
We're running an experiment with the [Behavior Insights Team](http://www.behaviouralinsights.co.uk). Will the inclusion of a letter at the front of the form increase the number of correctly filled out forms?

With letter - https://boston.seamlessdocs.com/f/zqz0n9kyn5hw
Without letter - https://boston.seamlessdocs.com/f/w1n3oosi6w1m

**Comment by joshuagee** [comment]
https://edit.boston.gov/50-liberty-affordable-housing-lottery-application

**Comment by Danchen-Xu** [comment]
@joshuagee Sorry for the confusion! Please only keep 1 BR, 2 BR, and 3 BR for this development.

**Comment by joshuagee** [comment]
This is good to go

**Comment by joshuagee** [comment]
https://edit.boston.gov/50-liberty-affordable-housing-application

**Comment by Danchen-Xu** [comment]
@joshuagee This one shows forbidden, too.

**Comment by joshuagee** [comment]
@Danchen-Xu I haven't published it yet.

**Comment by Danchen-Xu** [comment]
@joshuagee Sorry. Please let us know when it's published and ready to go.
