### ISSUE TITLE
Affordable Housing Lottery Application for Waterstone at the Circle 

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#416]
Hi Josh, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Friday, December 1, 2017

We need a RENTAL application for the following:

Distribution Period: Monday, December 4, 2017 - Friday, December 15, 2017

Development name: Waterstone at the Circle
Development Address: 399 Chestnut Hill Ave, Boston, MA 02135
Deadline to submit the application: December 22, 2017
Address to mail application: c/o Waterstone at the Circle, 27 Mica Lane, Wellesley, MA 02481 

Developer: Beth Anderson
Email: banderson@epochsl.com

Agent: John Costello
Email: waterstone@maloneyproperties.com
Telephone: 781-992-5303

Please Remove: 

Section 2:
- [x] Please remove studio and three bedrooms from bedroom types
- [x] Please remove disability questions, because there are no income-restricted units built out for persons with disability in this development

Section 4:
- [x] Please only keep the question regarding Boston Residency.

I have also attached the paper application. 

We will need the application by Friday,  December 1, 2017

Please also share the spreadsheet with jcostello@maloneyproperties.com

Thank you,

Danchen

**Comment by Danchen-Xu** [comment]
[Waterstone at the Circle Housing Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/1492659/Waterstone.at.the.Circle.Housing.Lottery.Application.pdf)

**Comment by joshuagee** [comment]
@Danchen-Xu Same question about bedroom types as #415

**Comment by joshuagee** [comment]
We're running an experiment with the [Behavior Insights Team](http://www.behaviouralinsights.co.uk). Will the inclusion of a letter at the front of the form increase the number of correctly filled out forms?

With letter - https://boston.seamlessdocs.com/f/3mb1oeg4b0gq
Without letter - https://boston.seamlessdocs.com/f/yjxwybsusvu7

**Comment by joshuagee** [comment]
https://edit.boston.gov/waterstone-circle-affordable-housing-lottery-application

**Comment by joshuagee** [comment]
https://edit.boston.gov/waterstone-circle-affordable-housing-lottery-application-0

**Comment by Danchen-Xu** [comment]
@joshuagee Thank you, Josh! But somehow the form shows 403 forbidden... Can you fix?
