### ISSUE TITLE
Affordable Housing Lottery Application for 30 B Street

### ISSUE THREAD

**Issue by AshleyShort** [CityOfBoston/Forms#417]
Hi Josh, 

Contact persons: Alexis Buckley, alexis.buckley@boston.gov and Ashley Short, ashley.short@boston.gov
Child of #376

We will need this by Friday 12/1/17

We need a SALE application for the following:

Distribution Period: 12/4/17-12/15/17

Development name: 30 B Street
Development Address: 30 B Street, South Boston, MA 02127
Deadline to submit the application: 12/22/17
Address to mail application: 27 Mica Lane, Attention 30 B Street, Wellesley, MA 02481

Developer: Charles Aggouris
Email: charles@gfcdevelopment.com

Agent: John Costello
Email: 30BStreet@maloneyproperties.com
Telephone: 781-992-5306

Please Remove: 

Section 2: 
- [x] Please remove 'Studio' bedroom option.
- [x] Please remove questions about ADA units (n/a because development has no units built for persons who have disabilities)
- [x] Please add 'Name of co-head of household and/or member 3 if applicable.'

Section 3: 
- [x] Please remove questions about housing assistance (n/a because development is a homeownership project)

Section4:
- [x] Please only include questions regarding first time home buyer and Boston residency. (Please remove questions regarding homelessness, artist certification, and age upon occupancy because this development does not have these preferences.)

I have also attached the paper application. 
[30 B Street Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/1492719/30.B.Street.Lottery.Application.pdf)

We will need the application by Friday 12/1/17

Please also share the spreadsheet with jcostello@maloneyproperties.com

Thank you,

**Comment by joshuagee** [comment]
Same question about rooms as #415 @Danchen-Xu

**Comment by joshuagee** [comment]
With letter - https://boston.seamlessdocs.com/f/cyx2phl5ot1b
Without Letter - https://boston.seamlessdocs.com/f/490a9e9owwp4

**Comment by joshuagee** [comment]
https://edit.boston.gov/30-b-street-affordable-housing-lottery-application

**Comment by joshuagee** [comment]
https://edit.boston.gov/30-b-street-affordable-housing-lottery-application-0

**Comment by AshleyShort** [comment]
@joshuagee Hi Josh, thank you for the online application. Things look great except for one correction. Could you please only include 1BR, 2BR, and 3BR options for household type? Please remove the studio, 4BR, 5BR, and 6BR options because the development does not include those options. Thank you for your help!
