### ISSUE TITLE
Affordable Housing Lottery Application for Telford 180

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#418]
Hi Josh, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Friday, December 1, 2017

We need a SALE application for the following:

Distribution Period: December 4, 2017 - December 15, 2017

Development name: Telford 180
Development Address: 180 Telford Street, Boston, MA 02135
Deadline to submit the application: December 22, 2017
Address to mail application: c/o Telford 180, 27 Mica Lane, Wellesley MA 02481

Developer: Stephen Davis
Email: sdavis@TheDavisCompanies.com

Agent: John Costello
Email: telford180@maloneyproperties.com
Telephone: 781-992-5301

Please Remove: 

Section 2:

- [x] please remove studio and one bedroom from the bedroom sizes
- [x] please remove the question regarding disabilities, because there are no income-restricted units designed for persons with disabilities in this development.

Section 3:

- [x] Please remove question regarding housing assistance, because this is a homeownership project.

Section4:

- [x] Please only keep first-time home buyer and Boston Residence questions in this section.

I have also attached the paper application. 
[180 Telford Housing Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/1492844/180.Telford.Housing.Lottery.Application.pdf)

We will need the application by Friday, December 1, 2017

Please also share the spreadsheet with jcostello@maloneyproperties.com

Thank you,

Danchen

**Comment by joshuagee** [comment]
@Danchen-Xu Same question about rooms as #415

**Comment by joshuagee** [comment]
We're running an experiment with the [Behavior Insights Team](http://www.behaviouralinsights.co.uk). Will the inclusion of a letter at the front of the form increase the number of correctly filled out forms?

With letter - https://boston.seamlessdocs.com/f/dc38chunvovw
Without letter - https://boston.seamlessdocs.com/f/7kvgzztv990v

**Comment by joshuagee** [comment]
https://edit.boston.gov/telford-180-affordable-housing-lottery-application

**Comment by joshuagee** [comment]
Script page wasn't working, so here's an article page: https://www.boston.gov/telford-180-affordable-housing-lottery-application-0
