### ISSUE TITLE
Affordable Housing Lottery Application for Port 45

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#419]
Hi Josh, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Friday, December 1, 2017

We need a SALE application for the following:

Distribution Period: Monday, December 4, 2017 - Friday, December 15, 2017

Development name: Port 45
Development Address: 45 West Third Street, South Boston, MA 02127
Deadline to submit the application: December 22, 2017
Address to mail application: c/o Port 45, 27 Mica Lane, Wellesley, MA 02481

Developer: William Anderson
Email:wanderson@metriccorp.com

Agent: John Costello
Email: jcostello@maloneyproperties.com
Telephone: 781-992-5304

Please Remove: 

Section 2:

- [x] Please remove studio and three bedrooms from bedroom sizes preference.
- [x] Please question regarding disabilities, because there are no units designated to persons with disabilities in this building.

Section 3:

- [x] Please remove the question regarding housing assistance, because this is a homeownership project.

Section4:

- [x] Please only keep first time home buyer and Boston residency questions in this section. 

I have also attached the paper application. 
[Port 45 Income Restricted Housing Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/1492881/Port.45.Income.Restricted.Housing.Lottery.Application.pdf)

We will need the application by Friday, December 1, 2017

Please also share the spreadsheet with jcostello@maloneyproperties.com

Thank you,

**Comment by joshuagee** [comment]
@Danchen-Xu Same question as #415

**Comment by joshuagee** [comment]
We're running an experiment with the [Behavior Insights Team](http://www.behaviouralinsights.co.uk). Will the inclusion of a letter at the front of the form increase the number of correctly filled out forms?

With letter - https://boston.seamlessdocs.com/f/1su0pngmff46
Without letter - https://boston.seamlessdocs.com/f/nq7vo02w8pt

**Comment by joshuagee** [comment]
https://edit.boston.gov/port-45-affordable-housing-lottery-application

**Comment by joshuagee** [comment]
https://edit.boston.gov/port-45-affordable-housing-lottery-application-0

**Comment by Danchen-Xu** [comment]
@joshuagee Hi Josh, can you please change the marketing agent's email for this development to Port45@maloneyproperties.com? I am very sorry for the inconvenience.

**Comment by joshuagee** [comment]
@Danchen-Xu all set
