### ISSUE TITLE
Affordable Housing Lottery Application for 367 Neponset 

### ISSUE THREAD

**Issue by AshleyShort** [CityOfBoston/Forms#421]
Contact person: Alexis Buckley, alexis.buckley@boston.gov and Ashley Short, ashley.short@boston.gov
Child of #376

We will need this by Friday 12/22/17

We need a RENTAL application for the following:

Distribution Period: 12/29/17-1/11/18

Development name: Residences at M (367 Neponset Avenue Project)
Development Address: 11 Minot Street, Dorchester, MA 02122
Deadline to submit the application: Friday 1/19/18
Address to mail application: Rooney Real Estate, 700 East Broadway, South Boston, MA 02127

Developer: Tanya Adamson
Email: tanyabarber@comcast.net

Agent: Jackie Rooney
Email: jackie@rooney-re.com
Telephone: 617-269-1000

Please Remove: 

Section 2: 

- [x] Please remove options for 'studio, 2, 3, 4, 5, & 6 BR' (n/a for this development) Please keep only the '1 bedroom' option.
- [x] Please remove questions regarding ADA units (n/a for this development)

Section 4:

- [x] Please only include questions regarding Boston residency. Please remove questions regarding homelessness, artist certification, first time home buyer, and age on the day of occupancy. 

I have also attached the paper application. 
[367 neponset paper application aka 11 Minot aka Residences at M.pdf](https://github.com/CityOfBoston/Forms/files/1533263/367.neponset.paper.application.aka.11.Minot.aka.Residences.at.M.pdf)

We will need the application by Friday 12/22/17

Please also share the spreadsheet with jackie@rooney-re.com

Thank you,

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/s9clgqmxw61

**Comment by joshuagee** [comment]
https://edit.boston.gov/367-neponset-affordable-housing-application

**Comment by AshleyShort** [comment]
Hi Josh,

Thank you so much! It looks great.  One note- under the "income and assets" section in the first sentence of the third paragraph, it says, "We know that income and fluctuate" which seems like a typo. Can this please be adjusted? Thank you!

**Comment by joshuagee** [comment]
OK -- I'm going to go ahead and publish

https://www.boston.gov/367-neponset-affordable-housing-application
