### ISSUE TITLE
Application for Boards and Commissions

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/Forms#427]
Contacts: 
Danny Green <danny.green@boston.gov>
Jake Hasson <jake.hasson@boston.gov>

Link: 
https://www.cityofboston.gov/boardsandcommissions/application/apply.aspx?bid=Boston%20Conservation%20Commission&pid=

**Comment by joshuagee** [comment]
James found the form, sent it to me. 

In March 2017 met with Danny and Jake to discuss making a SeamlessDoc. Turns out there's also a back-end system for managing the commission applicants and possibly board members. Tabled until we can deal with this as a web application. Didn't dig too hard into the back-end processes or interface.

**Comment by rachelbraun** [comment]
Too complicated for functionality. Solution being pursued elsewhere.
