### ISSUE TITLE
Affordable Housing Lottery Application for Walter Huntington Apartments

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#428]
Hi Josh, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and/ or Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Wednesday, 1/17/2018

We need a rental application for the following:

Distribution Period: January 19, 2018 – January 28, 2018

Development name: Walter Huntington Apartments
Development Address: 35 South Huntington Ave, Mission Hill, 02115
Deadline to submit the application: February 5, 2018
Address to mail application: Maloney Properties, Inc., Attention: Huntington Lottery, 27 Mica Lane, Wellesley MA 02481

Developer: Dan Maguire
Email: danmaguire123@gmail.com

Agent: John Costello
Email: Huntington@MaloneyProperties.com 
Telephone: 617-209-5407

Section 2: 

- [x] Please only keep 2 Bedroom

Section4:

- [x] Please only keep the Boston Residency Question

I have also attached the paper application. 
[Walter Huntington Apartments.pdf](https://github.com/CityOfBoston/Forms/files/1624598/Walter.Huntington.Apartments.pdf)

We will need the application by Wednesday, 1/17/2018

Please also share the spreadsheet with jcostello@maloneyproperties.com

Thank you,

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/8vtok3hkzjri

**Comment by joshuagee** [comment]
https://www.boston.gov/walter-huntington-apartments-affordable-housing-lottery-application
