### ISSUE TITLE
Affordable Housing Application for Lumen

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#429]
Hi Josh, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by  Wednesday, 1/17/2018

We need a sale application for the following:

Distribution Period: January 19, 2018 – January 28, 2018 

Development name: Lumen
Development Address: 30 Polk Street, Boston, MA 02129
Deadline to submit the application: February 5, 2018
Address to mail application: Maloney Properties, Inc., Attention: 30 Polk Street Lottery, 27 Mica Lane, Wellesley MA 02481

Developer: Caleb Manchester
Email: csm@gansettventures.com

Agent: John Costello
Email: 30Polk@maloneyproperties.com
Telephone: 617-209-5403 

Section 2:

- [x] Please only keep 1 Bedroom and 2 Bedroom

- [x] Please only keep Mobility Impairment option under the disability question, as there is one 1br unit built out for persons with mobility impairments

Section 3:

- [x] Please remove questions on housing assistance, as this is a home-ownership project

Section4:

- [x] Please keep question on First-time Home Buyer

- [x] Please keep question regarding Boston Residency
 
I have also attached the paper application. 
[Lumen Income Restricted Housing Application.pdf](https://github.com/CityOfBoston/Forms/files/1624636/Lumen.Income.Restricted.Housing.Application.pdf)

We will need the application by  Wednesday, 1/17/2018

Please also share the spreadsheet with jcostello@maloneyproperties.com

Thank you,

**Comment by joshuagee** [comment]
@Danchen-Xu Is that the correct email address? 30Polk@maloneyproperties.com

**Comment by joshuagee** [comment]
https://boston.seamlessdocs.com/f/t4v7fwfvpjjd

**Comment by Danchen-Xu** [comment]
@joshuagee yes, 30Polk@maloneyproperties.com is the correct email address. Thank you!

**Comment by joshuagee** [comment]
https://www.boston.gov/lumen-affordable-housing-lottery-application
