### ISSUE TITLE
Affordable Housing Application for Thread Hyde Park

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#433]
Hi James, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We used the template we created with Josh. Please let us know if there is anything that we can modify to smoothen the transition. Please also feel free to reach out if you have any questions!

We will need this by Tuesday, February 20th, 2018

We need a RENTAL application for the following:

Distribution Period: February 27, 2018, to March 9th, 2018

Development name: Thread Hyde Park
Development Address: 1582 River Street, Hyde Park, MA 
Deadline to submit the application: March 20th, 2018
Address to mail application: Insight Realty Group - Thread, 1429 Centre St, West Roxbury, MA 02132

Developer: Anthony Ruscito
Email: anthony@corvoproperties.com

Agent: Kris MacDonald
Email: applications@threadhydepark.com
Telephone: (617)326-8397

Section 2:

- [x] Please only keep 1 Bedroom and 2 Bedroom options here
- [x] Please remove questions on disabilities, as there are no ADA units in this development's income-restricted units portfolio.

Section4:

- [x] Please only keep the question regarding Boston Residency.

I have also attached the paper application. 
[Thread Hyde Park Standardized Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/1704309/Thread.Hyde.Park.Standardized.Lottery.Application.pdf)

We will need the application by Tuesday, February 20th, 2018

Please also share the spreadsheet with the marketing agent at kris@krismacdonald.com

Thank you,

Danchen

**Comment by jduffy2001** [comment]
@Danchen-Xu can you go through this application to make sure nothing is missing?

https://boston.seamlessdocs.com/f/1wrdvblaez81

**Comment by jduffy2001** [comment]
Link in Drupal: https://edit.boston.gov/thread-hyde-park-affordable-housing-lottery-application

**Comment by Danchen-Xu** [comment]
@jduffy2001 Hi James, 

Thank you so much for the help and updates. Alexis and I have both filled an application, and it looks good. 

At the same time, can you please help us change the language on the confirmation page to "​Thank you! Your application has been submitted. Please ​click on the envelope or arrow icons in the top right corner of this page to email​ yourself or download​ a copy of the application. We strongly recommend doing this!"

Please let me know if you have any questions! 

Thank you,

Danchen

**Comment by jduffy2001** [comment]
@alexisbuckley mentioned a thank you message at the end. @Danchen-Xu, could you send me the message you want added?
