### ISSUE TITLE
Income-restricted Housing Lottery Application Request - Aberdeen

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#439]
Hi James, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Monday, March 12, 2018

We need a sale application for the following:

Distribution Period: Tuesday, March 13, 2018 – Thursday, March 22, 2018

Development name: The Aberdeen
Development Address: 1605 Commonwealth Avenue, Boston, MA 02134
Deadline to submit the application: March 29, 2018
Address to mail application: Maloney Properties, Inc., Attention: Aberdeen Lottery, 27 Mica Lane, Wellesley MA 02481

Developer: Reid Joseph
Email: RJoseph@wbproperties.com

Agent: John Costello
Email: Aberdeen@maloneyproperties.com
Telephone: 781-992-5310

Section 2:

- [x] Please only keep one bedroom and two bedroom
- [x] Please remove questions regarding disabilities, as there are no ADA units in this development's income-restricted unit portfolio

Section 3:

- [x] Please remove questions on housing assistance, as this is a homeownership project

Section4:
Please only keep the following questions
- [x] First Time Home Buyer
- [x] Boston Residency

We will need the application by Monday, March 12, 2018

Please also share the spreadsheet with jcostello@maloneyproperties 

Thank you,

**Comment by jduffy2001** [comment]
@Danchen-Xu here's the Aberdeen application in seamless docs if you want to test:

https://boston.seamlessdocs.com/f/9bfdzk3ejybs

**Comment by jduffy2001** [comment]
Aberdeen is in Drupal, everything should be hooked up.
