### ISSUE TITLE
Income-restricted housing lottery application request - Penniman on the Park

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#440]
Hi James, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Monday, March 12, 2018

We need a SALE application for the following:

Distribution Period: Tuesday, March 13, 2018 – Thursday, March 22, 2018

Development name: Penniman on The Park
Development Address: 20 Penniman Road, Boston, MA 02134
Deadline to submit the application: March 29, 2018
Address to mail application: Maloney Properties, Inc., Attention: Penniman on The Park Lottery, 27 Mica Lane, Wellesley MA 02481

Developer: Steve Laverty
Email: slaverty@jumbocapital.com

Agent: John Costello
Email: Penniman@maloneyproperties.com
Telephone: 781-992-5309

Section 2:

- [x] Please only keep one bedroom and two bedroom
- [x] Please remove question regarding disability, as there are no ADA units in this development's income-restricted unit portfolio

Section 3:

- [x] Please remove questions on housing assistance, as this is a homeownership project

Section 4:
Please only keep the following questions
- [x] First-time homebuyer
- [x] Boston Residency

We will need the application by Monday, March 12th, 2018

Please also share the spreadsheet with jcostello@maloneyproperties

Thank you,

Danchen

**Comment by jduffy2001** [comment]
@Danchen-Xu here's the link in seamless docs:

https://boston.seamlessdocs.com/f/dik1ml8r15vx

**Comment by jduffy2001** [comment]
this is set up in Drupal
