### ISSUE TITLE
Income-Restricted Housing Lottery Application Request - Washington Street

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#441]
Hi James, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Monday, March 12th, 2018

We need a RENTAL application for the following: 

Distribution Period: Tuesday, March 13, 2018 – Thursday, March 22, 2018

Development name: 3383-3389 Washington Street
Development Address: 3383-3389 Washington Street, Boston, MA 02130
Deadline to submit the application: March 29, 2018
Address to mail application: Maloney Properties, Inc., Attention: Washington Street Lottery, 27 Mica Lane, Wellesley MA 02481

Developer: Justin Iantosca
Email: justin@arborviewcompanies.com

Agent: John Costello
Email: WashingtonStreet@MaloneyProperties.com
Telephone: 781-992-5311

Section 2:
- [x] Please only keep 1 bedroom and 2 bedroom
- [x] Please remove questions on disability, as there are no ADA units in this development's income-restricted units portfolio

Section 4:
- [x] Please only keep the questions on Boston Residency

We will need the application by Monday, March 12, 2018

Please also share the spreadsheet with jcostello@maloneyproperties.com

Thank you,

Danchen

**Comment by jduffy2001** [comment]
@Danchen-Xu here's the application in seamless docs:

https://boston.seamlessdocs.com/f/hwr6jbqoy2k

**Comment by jduffy2001** [comment]
this is set up in Drupal
