### ISSUE TITLE
Income-restricted housing lottery application request - Tilia

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#442]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Monday, March 12th, 2018

We need a SALE application for the following:

Distribution Period: Tuesday, March 13, 2018 – Thursday, March 22, 2018

Development name: Tilia
Development Address: 143-171 Hyde Park Avenue, Boston, MA 02130
Deadline to submit the application: March 29, 2018
Address to mail application: Maloney Properties, Inc., Attention: Tilia Lottery, 27 Mica Lane, Wellesley MA 02481

Developer: Eric Seitz
Email: eseitz@luzernassoc.com

Agent: John Costello
Email: Tilia@maloneyproperties.com
Telephone: 781-992-5312

Please Remove: 

Section 2:
- [x] Please only keep 2 bedrooms and 3 bedroom options
- [x] Please remove questions on disabilities, as there are no built-out ADA units in this development's income-restricted unit portfolio

Section 3:
- [x] Please remove questions on housing assistance, as this is a homeownership project

Section4: Please only keep the following questions
- [x] First Time Homebuyer
- [x] Boston Residency

We will need the application by Monday, March 12th, 2018

Please also share the spreadsheet with jcostello@maloneyproperties.com

Thank you,

Danchen

**Comment by jduffy2001** [comment]
@Danchen-Xu here's the link in seamless docs:

https://boston.seamlessdocs.com/f/1zhrvvkm11e3

**Comment by jduffy2001** [comment]
this is set up in Drupal
