### ISSUE TITLE
Income-restricted housing lottery application request - 70 Bremen

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#443]
Hi James, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Monday, March 12th, 2018

We need a SALE application for the following:

Distribution Period: Tuesday, March 13, 2018 – Thursday, March 22, 2018

Development name: 70 Bremen Street
Development Address: 70 Bremen Street, Boston, MA 02128
Deadline to submit the application: March 29, 2018
Address to mail application: Maloney Properties, Inc., Attention: 70 Bremen Street Lottery, 27 Mica Lane, Wellesley MA 02481

Developer: Paul Marks
Email: paulm@apartmentseastboston.com

Agent: John Costello
Email: 70Bremen@maloneyproperties.com
Telephone: 781-992-5307

Section 2: 
Please keep
- [x] Studio
- [x] 1 Bedroom
- [x] 2 Bedroom
- [x] 3 Bedroom

- [x] Please remove questions on disabilities, as there are no built-out ADA units in this development's income-restricted units portfolio

Section 3:

- [x] Please remove questions regarding housing assistance, as this is a homeownership project

Section 4: Please keep the following questions
- [x] First Time Homebuyer

- [x] Boston Residency

We will need the application by Monday, March 12, 2018

Please also share the spreadsheet with jcostello@maloneyproperties.gov

Thank you,

Danchen

**Comment by jduffy2001** [comment]
@Danchen-Xu here's the application in seamless docs:

https://boston.seamlessdocs.com/f/l1kvqux8va0c

**Comment by jduffy2001** [comment]
this is set up in Drupal
