### ISSUE TITLE
Income Restricted Housing Lottery Application Request - 99 Tremont Street

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#444]
Hi James, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Monday, March 12th, 2018

We need a SALE application for the following:

Distribution Period: Tuesday, March 13, 2018 – Thursday, March 22, 2018

Development name: 99 Tremont Street
Development Address: 99 Tremont Street, Boston, MA 02135
Deadline to submit the application: March 29, 2018
Address to mail application: Maloney Properties, Inc., Attention: 99 Tremont Lottery, 27 Mica Lane, Wellesley MA 02481

Developer: Ben Whitney
Email: ben@mainsailmgmt.com

Agent: John Costello
Email: 99Tremont@MaloneyProperties.com
Telephone: 781-992-5308 

Section 2:
Please keep the following bedroom sizes
- [x] 1 Bedroom
- [x] 2 Bedroom

- [x] Please keep the question on disabilities. There is one two bedroom unit built out for persons with mobility impairments

Section 3:

- [x] Please remove questions regarding housing assistance, as this is a homeownership project

Section4: Please keep the following questions

- [x] First Time Homebuyer
- [ ] Boston Residency

We will need the application by Monday, March 12, 2018

Please also share the spreadsheet with jcostello@maloneyproperties.com

Thank you profusely!

Best,

Danchen

**Comment by jduffy2001** [comment]
@Danchen-Xu here's the application in seamless docs:

https://boston.seamlessdocs.com/f/kasa1cq3cszt

**Comment by jduffy2001** [comment]
this is now in drupal
