### ISSUE TITLE
Income-Restricted Housing Application - 9 Williams

### ISSUE THREAD

**Issue by Danchen-Xu** [CityOfBoston/Forms#446]
Hi James, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Danchen Xu, danchen.xu@boston.gov
Child of #376

We will need this by Friday, April 20th.

We need a RENTAL application for the following:

Distribution Period: 4/23/18 to 5/07/18

Development name: 9 Williams Street Apartments
Development Address: 9 Williams Street, Roxbury, MA 02119
Deadline to submit the application: 5/15/18
Address to mail application: 207 Dudley Street Roxbury MA 02119 

Developer: Russell Tanner
Email: rtanner@madison-park.org

Agent: Genesa Patten
Email: 9williams@winnco.com
Telephone: 617-445-8338

Section 2:
- [x] Please only keep 2 Bedroom
- [x] Please only keep the option of deaf/hard of hearing - 2 bedroom

Section 4:
- [x] Please only keep Boston Residency question

I will share the pdf. version of the application with you via email shortly.

We will need the application by Friday, April 20th.

Please also share the spreadsheet with gpatten@winnco.com

Thank you,

**Comment by jduffy2001** [comment]
This is all set.
