### ISSUE TITLE
Affordable Housing Lottery Application - Harmon Apartments

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#447]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov, and diana.lamothe@boston.gov 
Child of #376

We will need this by Tuesday, 5/8/18

We need a RENTAL application for the following:

Distribution Period: 5/9/18-6/13/18

Development name: Harmon Apartments
Development Address: 2045 Dorchester Avenue, Dorchester
Deadline to submit the application: 6/15/18
Address to mail application: 536 Granite Street, Braintree, MA 02184

Developer: Tara Mizrahi. Affirmative Investments, Inc.
Email: tmizrahi@affirmativeinvestments.com 

Agent: Tamme Polson, Peabody Properties
Email: harmon@peabodyproperties.com
Telephone: 781-794-1046

Section 2:

- [ ] Please only keep 1 Bedroom and 2 Bedroom
- [ ]   Please only keep the option of deaf/hard of hearing + vision impairment - 1-bedroom 
- [ ]   AND Mobility - 1-bedroom + 2-bedroom

Section 4:

- [ ] Please add the extra questions/checklist for persons with disabilities (4a, 4a-1 and 4a-2 in the paper version)

- [ ] Please keep above and only the Boston Residency Preference

I will share the pdf and Google Doc version of the application with you via email shortly.

We will need the application by Tuesday, May 8.

Please also share the spreadsheet with harmon@peabodyproperties.com in VIEW ONLY

Thank you,

**Comment by jduffy2001** [comment]
This is all set.
