### ISSUE TITLE
Walker Park Apartments Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#448]
--Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Diana Lamothe, diana.lamothe@boston.gov
Child of #376

We will need this by June, 4 2018 
We need a rental application for the following:

Distribution Period: June 4, 2018 - July 6, 2018
----
Development name: Walker Park Apartments
Development Address: 67 & 80 Walnut Park Roxbury, MA Deadline to submit the application:
Address to mail application: 9 Wardman Road-Rear, Roxbury, MA 02119

Developer: Frank Shea, Urban Edge
Email: fshea@urbanedge.org

Agent: Hector Cruz
Email: hcruz@winnco.com
Telephone: 617-989-1052
--
(USE CHECK BOX FUNCTION IN GITHUB HERE)

Section 2:
Please only keep 

- [ ] 1 bedroom

- [ ] 2 bedroom

- [ ] 3 bedroom

As there are only 1 bedrooms for ADA vision impairment and 1 bedrooms ADA deaf/hard of hearing in this development, please only keep the options of 

- [ ] Deaf/Hard of Hearing 

- [ ] 1 bedroom

- [ ] Vision Impairment

- [ ] 1 Bedroom

Section 4:
Please only keep questions regarding 

- [ ] Boston Residency

We will need the application by June, 4 2018 

Please also share the spreadsheet in View Only with dmcgovern@winnco.com 

Thank you,
Alexis

**Comment by jduffy2001** [comment]
This is in Drupal now.
