### ISSUE TITLE
Rental Housing Lottery Application 132 Chestnut Hill Ave

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#449]
“Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Diana Lamothe, diana.lamothe@boston.gov 

Child of #376

We will need this by July 2, 2018
We need a RENTAL application for the following:

Distribution Period: July 2, 2018 - September 7, 2018

Development name: Weinberg House
Development Address: 132 Chestnut Hill Avenue
Deadline to submit the application: September 7, 2018
Address to mail application: 40 Wallingford Road, Brighton, MA 02135

Developer: Rhonda Spector
Email: rspector@jche.org

Agent: Jill Ouellette
Email: msheynberg@jche.org
Telephone: 617-912-8421

(USE CHECK BOX FUNCTION IN GITHUB HERE)

Section 2:
Please only keep 
- [ ] Studio 

- [ ] One Bedroom

As there are only Mobility Studios, Mobility One Bedrooms, and Vision Impaired One Bedroom in this development, please only keep the options of

- [ ]  ADA Mobility Studios 

- [ ] ADA Mobility One Bedroom

- [ ] ADA Vision Impairment One Bedroom

Section 4:
Please only keep questions regarding the following preferences: 

- [ ] elderly (62+)

- [ ] Boston Residency

- [ ] Disability

We will need the application by July 2nd, 2018

Please also share the spreadsheet in View Only with msheynberg@jche.org
Thank you,
Diana

**Comment by jduffy2001** [comment]
This is drafted in Drupal.
