### ISSUE TITLE
Paris Village Rental Housing Lottery Application 

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#450]
Contact person: Alexis Buckley, alexis.buckley@boston.gov and Diana Lamothe, diana.lamothe@boston.gov 
Child of #376

We will need this by July 23, 2018

We need a RENTAL application for the following:

Distribution Period: July 23 to August 27, 2018

Development name: Paris Village
Development Address: 191 Paris Street, East Boston Ma 02128
Deadline to submit the application: August 24, 2018
Address to mail application: 201 Sumner Street, East Boston MA 02128

Developer: East Boston Community Development Corporation; Albert Cadarelli
Email: acaldarelli@ebcdc.com

Agent:Erin Nanstad
Email: enanstad@ebcdc.com
Telephone:617-567-7755

Section 2:
Please only keep 

- [ ] 2 Bedroom
- [ ] 3 Bedroom

As there are only ADA Mobility Impairments  with 2 bedrooms and 3 bedrooms, ADA Deaf/Hard of Hearing with 2 Bedrooms in this development, please only keep the options of 

- [ ] 2 Bedroom with ADA Mobility Impairment
- [ ] 3 Bedroom with ADA Mobility Impairment
- [ ] 2 Bedroom with ADA Deaf/Hard of Hearing

Section 4:
Please only keep questions regarding 

- [ ] Boston Residency
- [ ] Homelessness

We will need the application by July 2, 2018

Please also share the spreadsheet in View Only with enanstad@ebcdc.com

Thank you,
Diana Lamothe

**Comment by jduffy2001** [comment]
This is set up in Drupal
