### ISSUE TITLE
728 E Broadway Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#452]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Diana Lamothe, diana.lamothe@boston.gov
Child of #376

We will need this by July 17, 2018 

We need a RENTAL  application for the following:

Distribution Period: July 17, 2018- July 26, 2018

Development name: 728 East Broadway
Development Address: 728 East Broadway, Boston MA 02127
Deadline to submit the application: August 2, 2018
Address to mail application: Maloney Properties, Inc. Attention: 728 East Broadway Lottery
27 Mica Lane Wellesley, MA 02481 

Developer: 726-734 East Broadway Realty, LLC; Joey Arcari
Email: joey@taverninthesquare.com

Agent: John Costello
Email: jcostello@maloneyproperties.com
Telephone:617-209-5250

Section 2:
Please only keep

- [ ] 1 bedroom

- [ ] 2bedroom

Section 4:
Please only keep questions regarding 

- [ ] Boston Residency

We will need the application by August 2, 2018

Please also share the spreadsheet in View Only with jcostello@maloneyproperties.com

Thank you,
Diana Lamothe

**Comment by duffy-james** [comment]
This is drafted
