### ISSUE TITLE
110 Broad st ( The Boulevard) Housing Ownership Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#453]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Diana Lamothe, diana.lamothe@boston.gov
Child of #376

We will need this by July 17, 2018

We need a SALE application for the following:

Distribution Period: July 17, 2018- July 26, 2018

Development name: The Boulevard
Development Address: 110 Broad Street, Boston MA 02110
Deadline to submit the application: August 2, 2018
Address to mail application: Maloney Properties Inc., Attention: The Boulevard Lottery,27 Mica Lane, Wellesley MA 02481

Developer: Marc Savatsky
Email: MSavatsky@newbostonventures.com

Agent: John Costello
Email: jcostello@maloneyproperties.com
Telephone: 617-209-5250

Section 2:
Please only keep

- [ ] 1 Bedroom 

As there are only 1  1 bedroom ADA unit built out for mobility impairments in this development, please only keep the options of 

- [ ] 1 Bedroom ADA Mobility Impairment

Section 3:

- [ ] Please remove the question on housing assistance

Section 4:
Please only keep questions regarding 

- [ ] BostonResidency

- [ ] BRACertified Artist

- [ ] FirstTime Home Buyer

We will need the application by August 2, 2018

Please also share the spreadsheet in View Only with jcostello@maloneyproperties.com

Thank you,
Diana Lamothe

**Comment by duffy-james** [comment]
Drafted in Drupal
