### ISSUE TITLE
39 A Street Home Ownership Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#454]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Diana Lamothe, Diana.lamothe@boston.gov
Child of #376

We will need this by July 17, 2018 

We need a SALE application for the following:

Distribution Period: July 17-26, 2018

Development name: 39 A Street
Development Address: 39 A Street, South Boston MA 02127
Deadline to submit the application: August 2, 2018
Address to mail application:27 Mica Lane, Wellesley MA 02481

Developer: 42 Silver Street, LLC; Charles McCarthy
Email: mccarthycharles2011@gmail.com

Agent: John Costello, Maloney Properties
Email: 39AStreet@maloneyproperties.com
Telephone:781-992-5317

Section 2:
Please only keep

- [ ] Studio

- [ ] 2 Bedroom

Section 3:

- [ ] Please remove the question on housing assistance

Section 4:
Please only keep questions regarding 

- [ ] FirstTime Home Buyer

- [ ] Boston Residency 

We will need the application by August 2, 2018

Please also share the spreadsheet in View Only with jcostello@maloneyproperties.com 

Thank you,
Diana Lamothe

**Comment by duffy-james** [comment]
Drafted in Drupal
