### ISSUE TITLE
Residences at Fairmount Station Rental Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#455]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Diana Lamothe, Diana.lamothe@boston.gov
Child of #376

We will need this by July 30, 2018

We need a RENTAL application for the following:

Distribution Period: July 30, 2018- August 27, 2018

Development name: Residences at Fairmount Station
Development Address: 11 Nott Street, Hyde Park, MA 02136
Deadline to submit the application: August 27, 2018
Address to mail application: 39 Maple Street, Hyde Park, MA  02136

Developer: Southwest Boston Community Development Corporation: Dave Traggorth
Email:dave@traggorthcompanies.com

Agent: Michael Baldwin
Email:RAFS@MaloneyProperties.com
Telephone:(617) 364-4388   

Section 2:
Please only keep

- [ ] Studio

- [ ] 1 Bedroom

- [ ] 2 Bedroom
		
- [ ] 3Bedroom

As there are only 1 bedroom with ADA Mobility Impairments and 2 bedroom with ADA Mobility Impairments; 1 bedroom with ADA Deaf/ Hard of Hearing / Visual Impairments in this development, please only keep the options of

- [ ] 1 bedroom with ADA Mobility Impairments

- [ ] 2 bedroom with ADA Mobility Impairments

- [ ] 1 bedroom with ADA Deaf/ Hard of Hearing / Visual Impairments

Section 4:
Please only keep questions regarding 

- [ ] Boston Residency

We will need the application by July 30, 2018

Please also share the spreadsheet in View Only with mbaldwin@maloneyproperties.com

Thank you,
Diana Lamothe

**Comment by duffy-james** [comment]
This is in Drupal
