### ISSUE TITLE
Bartlett Place Building B Rental Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#456]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Diana Lamothe, Diana.Lamothe@boston.gov
Child of #376

We will need this by Monday, 07/30/18 

We need a RENTAL application for the following:

Distribution Period: 07/30/18-08/26/18

Development name: Bartlett Place Building B
Development Address:2565 Washington Street, Roxbury MA 02119
Deadline to submit the application: September 4, 2018
Address to mail application: Winn Management, Marketing Office; 233 Blue Hill Avenue, Roxbury MA 02119

Developer: Nuestra Comunidad Development Corporation
Email: dclark@nuestracdc.org

Agent: Michael Cosgrove
Email: LNash@winnco.com
Telephone: 617-442-8472

Section 2:
Please only keep 

- [ ] 1 Bedroom

- [ ] 2 Bedroom

- [ ] 3 Bedroom

As there are only 1 bedroom ADA Hard of hearing/deaf and visually impaired, 2 bedroom ADA mobility Impairments, 3 bedroom ADA Hard of Hearing/deaf and visually impaired in this development, please only keep the options of 

- [ ] 1 bedroom ADA Hard of hearing/deaf and visually impaired

- [ ] 2bedroom ADA mobility Impairments

- [ ] 3 bedroom ADA Hard of Hearing/deaf and visually impaired 

Section 4:
Please only keep questions regarding

- [ ] Boston  Residency

- [ ] Homelessness

We will need the application by July 30, 2018

Please also share the spreadsheet in View Only with Jeffery Stigliano, jstigliano@winnco.com

Thank you,
Diana Lamothe

**Comment by duffy-james** [comment]
This is in Drupal.
