### ISSUE TITLE
Lantera, 125 Guest Street Rental  Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#457]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov and Diana Lamothe, diana.lamothe@boston.gov
Child of #376

We will need this by Thursday, July 26, 2018 

We need a RENTAL application for the following:

Distribution Period: 07-26-18 to 08-06-18

Development name: Lantera
Development Address: 125 Guest Street, Brighton MA 02135
Deadline to submit the application: 08-13-18
Address to mail application: 257 hillside ave, Needham MA 02494

Developer: Rail Spur LLC; James M. Halliday
Email: info@nbdevelopment.com

Agent: Brian Engler
Email: brian@s-e-b.com
Telephone: 617-782-2300 x203

Section 2:
Please only keep 

- [ ] Studio

- [ ] 1Bedroom

- [ ] 2Bedroom

- [ ] 3 Bedroom

As there are only 1 1-bedroom ADA Mobility Impairments, 1 1-bedroom ADA Deaf/Hard of Hearing, and 1 2-bedroom ADA Deaf/Hard of Hearing in this development, please only keep the options of 
 

- [ ] ADA Mobility Impairment 1 1-bedroom

- [ ] ADADeaf/Hard of Hearing 1 1-bedroom

- [ ] ADADeaf/Hard of Hearing 1 2-bedroom

Section 4:
Please only keep questions regarding 

- [ ] BostonResidency

We will need the application by July 26, 2018

Please also share the spreadsheet in View Only with brian@s-e-b.com

Thank you,
Diana Lamothe

**Comment by duffy-james** [comment]
This is drafted in Drupal.
