### ISSUE TITLE
The Union 48 Boylston Street Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#458]
Hi James, 

Contact person: NAME, EMAIL ADDRESS

Child of #376

We will need this by Friday, August 3, 2018

We need a RENTAL application for the following:

Distribution Period: Monday, August, 6, 2018 - Monday August 27, 2018

Development name: 48 Boylston Street
Development Address: 48 Boylston Street, Boston, MA 02116
Deadline to submit the application: Monday, August 27, 2018

Address to mail application: Maloney Properties, Inc., 27 Mica Lane, Wellesley,  MA  02481, attention: The Union

Developer:  The St. Francis House 
Email: klafrazia@stfrancishouse.org
Telephone:  617-654-1214

Agent: Lynn M. Delidow, Maloney Properties, Inc. 
Email: ldelidow@maloneyproperties.com 
Telephone:617-209-5259

Section 2: 
2a: PLEASE REMOVE
- [x] 2BR,
- [x] 3BR,
- [x] 4BR,
- [x] 5BR, and 
- [x] 6BR 

2b-1: Edit Mobility:
PLEASE INCLUDE 
- [x]  Mobility Studio and
- [x] Mobility 1BR.
PLEASE REMOVE
- [x] Deaf/Hard of Hearing and 
- [x] Vision Impairments 
Section 3: 

Section 4:
Remove the following preferences: Artist certification, First time home buyer, 62+ Occupancy 

I have also attached the paper application. (ATTACH PAPER APPLICATION)

We will need the application by Friday, August 3, 2018

Please also share the spreadsheet with alexis.buckley@boston.gov and she'll share it with the owner or her agents

Thank you,
 Alexis

[Rental Housing Lottery Application 48 Boylston Street.pdf](https://github.com/CityOfBoston/Forms/files/2233732/Rental.Housing.Lottery.Application.48.Boylston.Street.pdf)

**Comment by duffy-james** [comment]
This is in Drupal
