### ISSUE TITLE
Coppersmith Village Rentals

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#459]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by Monday, 7/30/18 

We need a RENTAL  application for the following:

Distribution Period: 7/31/18 - 8/27/18

Development name: Coppersmith Village 
Development Address: 9-101 Border Street 
Deadline to submit the application: 8/29/18
Address to mail application: Peabody Properties, Inc., ℅ Coppersmith Village Lottery, 536 Granite St., Braintree, MA 02184

Developer: Phil Giffee,  Neighborhood of Affordable Housing (NOAH)
Email: pgiffee@noahcdc.org
Telephone: 617-418-8240

Agent: Tamme Polson,  Peabody Properties 
Email: tpolson@peabodyproperties.com
Telephone: 781-794-1016
Please Remove: (USE CHECK BOX OPTION IN GITHUB HERE)

Section 2: 

- [ ] 2b. Remove 

- [ ] Micro, 
- [ ] Studio, 
- [ ] 4BR, 
- [ ] 5BR, 
- [ ] 6BR 

- [ ] 2B. Remove 
- [ ] Vision Impairments 

- [ ] both mobility and deaf/hard of hearing units have 1 bedroom and 2 bedrooms units. 

Section 3: 

Section 4: 
4: Remove the following questions: Homelessness

- [ ] Artist Certifications
- [ ] First Time Home Buyer
- [ ] 62+ Year Old Occupancy

I have also attached the paper application. 

We will need the application by 7/30/18

Please also share the spreadsheet with alexis.buckley@boston.gov and affirmativemarketing@boston.gov. Alexis will share w/ the approved owner's reps.

[Standardized Lottery Application Coppersmith (1).pdf](https://github.com/CityOfBoston/Forms/files/2241360/Standardized.Lottery.Application.Coppersmith.1.pdf)

Thank you,

ab

**Comment by duffy-james** [comment]
This is in Drupal
