### ISSUE TITLE
Community Stabilization Project Rental Housing Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#460]
Hi James, 

Contact person: alexis, alexis.buckley@boston.gov

Child of #376

We will need this by ASAP (**SORRY**)

We need a RENTAL application for the following:

Distribution Period: 08-02-2018 - 08-12-18

Development name:  Community Stabilization Project
Development Address:  49 Speedwell St., Dorchester, MA 02122 and 63 Hartford St., Dorchester, MA 02125
Deadline to submit the application: 08-15-18
Address to mail application: COHIF 1803 Dorchester Avenue, Dorchester, MA 02124

Developer:  Coalition for Occupied Homes in Foreclosure, Inc.
Email: paul@cohif.org
Telephone 617-237-6015

Agent: Coalition for Occupied Homes in Foreclosure, Inc.
Email: paul@cohif.org
Telephone: 617-237-6015

Section 2: Leave in:
 1 

- [ ] Bedroom
- [ ]  3 bedroom 
- [ ] 4 bedroom 
- [ ] 5 bedroom

Section 2b Please leave in: 

- [ ] Mobility
- [ ] 1 Bedroom

Section 3: 

- [ ] Please leave references to housing assistance

Section 4 - Please leave the following preferences: 

- [ ] City of Boston Resident
I have also attached the paper application. (ATTACH PAPER APPLICATION)

We will need the application by ASAP (SORRY!!!)

Please also share the spreadsheet with alexis.buckley@boston.gov and affirmativemarketing@boston.gov 

Thank you,

[Community Stabilization Project Lottery Application cm.pdf](https://github.com/CityOfBoston/Forms/files/2251121/Community.Stabilization.Project.Lottery.Application.cm.pdf)

**Comment by duffy-james** [comment]
This is in Drupal
