### ISSUE TITLE
345 Harrison Income Restricted Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#461]
Hi James, 

Contact person: alexis buckley, alexis.buckley@boston.gov

Child of #376

We will need this by Monday, August 13, 2018

We need a rental application for the following: 345 Harrison

Distribution Period: August 16, 2018- August 27, 2018

Development name: 345 Harrison
Development Address: 345 Harrison Ave, Boston MA 02118
Deadline to submit the application: Tuesday, September 4, 2018
Address to mail application: 345 Harrison Lottery ℅ SEB, 257 Hillside Ave, Needham MA 02494

Agent: Brian Engler
Email: brian@s-e-b.com
Telephone: 617-782-6900

Developer: Elizabeth Likovich
Email: elikovich@udr.com
Telephone: 720-283-6120

Section 2: Leave in 

- [ ] 1BR
- [ ] 2BR
- [ ] 3BR

Section 3: 

- [ ] Leave in Disability Question
- [ ] Mobility
- [ ] 1BR
- [ ] Add 3BR

- [ ] Deaf/Hard of Hearing
- [ ] 1BR
- [ ] 2BR

Section 4:

- [ ] Leave in only Boston Residency Preference

I have also attached the paper application.

We will need the application by Monday, August 13, 2018

Please share the spreadsheet with alexis at alexis.buckley@boston.gov and affirmativemarketing@boston.gov. We will share it with the owner and her agent. 

Thank you,

[345 Harrison Affordable_Income Restricted Housing Lottery Application-2 copy.pdf](https://github.com/CityOfBoston/Forms/files/2255783/345.Harrison.Affordable_Income.Restricted.Housing.Lottery.Application-2.copy.pdf)

**Comment by duffy-james** [comment]
This is in Drupal
