### ISSUE TITLE
150 West Broadway Home Ownership Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#462]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov, affirmativemarketing@boston.gov
Child of #376

We will need this by 8/12/18 

We need a SALE application for the following:

Distribution Period: 8/13/18 - 8/22/18

Development name: 150 West Broadway
Development Address: 150 West Broadway, South Boston, MA 02127
Deadline to submit the application: 8/31/18
Address to mail application: Maloney Properties, Inc., Attention: 150 West Broadway Lottery, 27 Mica Lane, Wellesley MA 02481

Developer: Joe Hassell
Email: bostonrealestatecapital@gmail.com 

Agent: John Costello, Maloney Properties
Email: WestBroadway@MaloneyProperties.com
Telephone: 781-992-5304 

Section 2:
Please only keep 
- [ ]1 Bedroom
- [ ] 2 Bedroom

- [ ] There are no units built out for persons with disabilities. Please remove those sections

Section 3:

- [ ] Please REMOVE the question on housing assistance

Section 4:

- [ ] Please only keep questions regarding 
- [ ] Boston Residency Preference
- [ ] First Time Home

 Buyer Preference

We will need the application by 8/12/18

Please also share the spreadsheet with alexis.buckley@boston.gov and affirmativemarketing@boston.gov. Alexis will share with the developer or her agent in view only.

Thank you!

[150 West Broadway Income Restricted  Housing Lottery Application-2 copy.pdf](https://github.com/CityOfBoston/Forms/files/2272746/150.West.Broadway.Income.Restricted.Housing.Lottery.Application-2.copy.pdf)

**Comment by duffy-james** [comment]
In Drupal
