### ISSUE TITLE
Portside East Pier Phase II Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#464]
Hi James, 

Contact person: alexis, alexis.buckley@boston.gov, affirmativemarketing@boston.gov 
Child of #376

We will need this by 8/17/18

We need a RENTAL application for the following:

Distribution Period:  Monday, 8/20/18 - Wednesday, 8/29/18

Development name:  Portside at Pier One
Development Address:  50 Lewis Street, East Boston, MA 02128
Deadline to submit the application: September 7, 2108
Address to mail application: Maloney Properties, Inc.
Attention: Portside Lottery, 27 Mica Lane, Wellesley MA 02481 

Developer:  Frank McAdams
Email:  fmcadams@roselandres.com 
Telephone 617-561-9500

Agent: John Costello, Maloney Properties
Email: portside@maloneyproperties.com 
Telephone: 617-209-5302 
					

Please Leave: 

Section 2 Please leave in: 

- [ ] Studio 
- [ ] 1 Bedroom
- [ ] 2 Bedroom

- [ ] Leave in Disabilities question
- [ ] Mobility 
- [ ] 1 Bedroom
- [ ] 2 Bedroom

- [ ] Deaf/Hard of Hearing
- [ ] Studio
- [ ] 1 Bedroom
- [ ] 2 Bedroom

Section 4:
Leave in Boston Residency only Please

I have also attached the paper application. (ATTACH PAPER APPLICATION)

We will need the application by DATE

Please also share the spreadsheet with alexis.buckley@boston.gov, and affirmativemarketing@boston.gov 

Thank you!!

[Portside East Pier Standardized Lottery Application copy.pdf](https://github.com/CityOfBoston/Forms/files/2281411/Portside.East.Pier.Standardized.Lottery.Application.copy.pdf)

**Comment by duffy-james** [comment]
in drupal
