### ISSUE TITLE
320 Maverick Home Ownership Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#465]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov, affirmativemarketing@boston.gov 
 
Child of #376

We will need this by Friday, August 17, 2018 

We need a sale application for the following:

Distribution Period: August 20-August 29, 2018

Development name: 320 Maverick Street
Development Address: 320 Maverick Street, East Boston, MA 02128
Deadline to submit the application: September 7, 2018
Address to mail application: Maloney Properties, Inc. ATTENTION 320 Maverick Lottery, 27 Mica Lane, Wellesley, MA 02481

Developer: Joe Ricupero ,Three Twenty Maverick Street LLC
Email: joericupero@capitolws.com

Agent: John Costello, Maloney Properties
Email: MaverickStreet@maloneyproperties.com
Telephone: 781-992-5306 

Section 2:
Please only keep 

- [ ] one bedroom
- [ ] two bedroom

- [ ] there are no units built out for persons w/ disabilities, please remove those questions

Section 3:

- [ ] Please REMOVE housing assistance/voucher questions

Section 4:
Please only keep questions regarding preferences for 

- [ ] Boston Residents,
- [ ] first time homebuyers.

We will need the application by August 17, 2018

Please also share the spreadsheet with alexis.buckley@boston.gov and affirmativemarketing@boston.gov 

Thank you!!

[320 Maverick at Jeffries Point Affordable_Income Restricted  Housing Lottery Application copy.pdf](https://github.com/CityOfBoston/Forms/files/2281430/320.Maverick.at.Jeffries.Point.Affordable_Income.Restricted.Housing.Lottery.Application.copy.pdf)

**Comment by duffy-james** [comment]
this is in Drupal
