### ISSUE TITLE
14 West Broadway Income Restricted Home Ownership Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#468]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov and affirmativemarketing@boston.gov

Child of #376

We will need this by Monday, September 10, 2018 
We need a SALE application for the following:

Distribution Period: September 13th, 2018 - September 24th, 2018

Development name: 14 West Broadway
Development Address: 14 West Broadway
Deadline to submit the application: October 6, 2018
Address to mail application: 300 A Street, Suite 101, Boston, MA 02210

Developer: CPC Cornerstone Development, LLC
Email: kmcmanama@citypointcapital.com

Agent: Kelly McManama
Email: 14westbroadwaysales@gmail.com
Telephone: 857-267-3346

Section 2:
Please only keep 
1 bedr

- [x] oom
- [x] 2 bedroom

There are no units built out for persons with disabilities, 

- [x] Please Remove the Disabilities Questions 

Section 3:

- [x] Please remove the question on housing assistance

Section 4:
 Please only keep questions regarding 

- [x] first time home buyer and 
[14 West Broadway Standardized Lottery Application

- [x] Boston residency

We will need the application by Monday, September 10, 2018

Please share the spreadsheet with Alexis at alexis.buckley@boston.gov and affirmativemarketing@boston.gov. Alexis will share it, in view only, with the appropriate parties.

Thank you,

[14 West Broadway Standardized Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/2350201/14.West.Broadway.Standardized.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
this is in Drupal
