### ISSUE TITLE
31 Orleans Home Ownership Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#470]
Hi James, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov 

Child of #376

We will need this by Monday, 9/24/18

We need a sales  application for the following:

Distribution Period: 9/24/18 - 10/3/18

Development name: 31 Orleans Street
Development Address: 31 Orleans Street, East Boston MA 02129
Deadline to submit the application: 10/10/18
Address to mail application: Maloney Properties, Inc. Attention 31 Orleans Street Lottery, 27 Mica Lane, Wellesley, MA 02481

Developer: Kieran McAllen
Email: kieranmcallen@yahoo.com
Telephone: 617-201-4781

Agent: John Costello
Email: jcostello@maloneyproperties.com
Telephone: 617-209-5250

Please Remove: (USE CHECK BOX OPTION IN GITHUB HERE)

Section 2: 

- [ ] Please remove all but 2 bedroom

- [ ] There are no ADA units so please remove disability prompts.

Section 3: 

- [ ] Please remove the questions about housing assistance

Section 4:
Please remove all but:

- [ ] Boston Residency
- [ ] First Time Home Buyer

I have also attached the paper application. 

We will need the application by Monday, 9/24/18

Please also share the spreadsheet with the following people:in view only: alexis.buckley@boston.gov, Doris Lin dlin@maloneyproperties.com ; Magda Janicki mjanicki@maloneyproperties.com and john costello, jcostello@maloneyproperties.com 

[31 Orleans Street Affordable%2FIncome Restricted  Housing Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/2403364/31.Orleans.Street.Affordable.2FIncome.Restricted.Housing.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
