### ISSUE TITLE
88 Wareham Home Ownership Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#471]
Hi James, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov 

Child of #376

We will need this by September 27, 2018

We need a Sale application for the following:

Distribution Period: September 27, 2018 - October 9, 2018

Development name: 88 Wareham Condominiums
Development Address: 88 Wareham Street, Boston MA
Deadline to submit the application: October 16, 2018
Address to mail application: SEB, Attention 88 Wareham Lottery, 257 Hillside Avenue, Needham, MA 02494

Developer: John H. Baxter
Email: Jbaxter@cressetgroup.com
Telephone: 617-624-9100

Agent: Brian Engler
Email: brian@s-e-b.com
Telephone: 617-782-2300 x203

Section 2: 
Please remove:

- [ ] 2 Bedroom
- [ ] 3 Bedroom
- [ ] 4 Bedroom
- [ ] 5 Bedroom
- [ ] 6 Bedroom

- [ ] Please remove all questions regarding disabilities

Section 3: 

- [ ] Please remove questions about housing assistance

Section 4:
Please remove all except:

- [ ] Boston Residency
- [ ] First Time Homebuyer

I have also attached the paper application. 
We will need the application by 9/27/18

- [ ] Please also share the spreadsheet in view only with alexis.buckley@boston.gov, info@sebhousing.com , and brian@s-e-b.com 

Thank you!

[88 Wareham Condominiums Affordable%2FIncome Restricted  Housing Lottery Application .pdf](https://github.com/CityOfBoston/Forms/files/2403425/88.Wareham.Condominiums.Affordable.2FIncome.Restricted.Housing.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
