### ISSUE TITLE
The Andi South Bay Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#472]
Hi James, 

Contact person: Alexis Buckley, alexis.buckley@boston.gov 

Child of #376

We will need this by September 27, 2018

We need a Rental application for the following:

Distribution Period: September 27, 2018 - October 9, 2018

Development name: South Bay Apartments
Development Address: 101 Allstate Road, Boston MA 02125
Deadline to submit the application: October 16, 2018
Address to mail application: SEB, Attention: The Andi Lottery, 257 Hillside Avenue, Needham, MA 02494

Developer: Adelaide Grady
Email: agrady@pritzkerrealty.com
Telephone: 704-999-7315

Agent: Brian Engler
Email: brian@s-e-b.com
Telephone: 617-782-2300 x203

Section 2: 
Please remove: 
4 bedroom
5 bedroom
6 bedroom

Please remove vision impairment

Please ADD to the mobility impairment unit types 
Studio
3 bedroom

Please ADD to the deaf/hard of hearing unit type:
3 bedroom

And REMOVE from the deaf/hard of hearing unit type: 
1 bedroom 
2 bedroom

Section 4
Please remove all but Boston Resident:

I have also attached the paper application 
We will need the application by 9/27/18

Please also share the spreadsheet in view only with alexis.buckley@boston.gov, info@sebhousing.com , and brian@s-e-b.com 

Thank you,
[South Bay Apartments Affordable%2FIncome Restricted  Housing Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/2403452/South.Bay.Apartments.Affordable.2FIncome.Restricted.Housing.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
