### ISSUE TITLE
Residences on E Income Restricted Home Ownership  Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#473]
Contact person: Alexis Buckley, alexis.buckley@boston.gov

Child of #376

We will need this ASAP 

We need a Sales application for the following:

Distribution Period: 10/9/18-11/2/18

Development name:  Residences on E
Development Address:  205 E Street, South Boston
Deadline to submit the application: 11/2/18
Address to mail application:Rooney Real Estate, Attention 205 E St. Lottery,  700 East Broadway, South Boston, MA 02127

Developer:  Paul Adamson, School Zone LLC
Email:  pauladamson@comcast.net
Telephone (617) 592-5323

Agent: Jackie Rooney
Email: jackie@rooney-re.com
Telephone:(617) 645-5370 

Section 2: only keep 

- [ ] 1 bedroom
- [ ] 2 bedroom

Please remove all  disabled units questions

Section 3: 3f-

- [ ] Please remove all questions to do with housing assistance

Section 4: 
Please remove 

- [ ] artist certification, 
- [ ] homeless, and 
- [ ] age question

Please leave only the 

- [ ] First Time Home buyer
- [ ] Boston Residency 
- [ ] 

I have also attached the paper application. 

We will need the application ASAP

Please also share the spreadsheet in view only 
with jackie@rooney-re.com and alexis.buckley@boston.gov 

Thank you,

[Standardized Lottery Application- Residences on E.pdf](https://github.com/CityOfBoston/Forms/files/2460745/Standardized.Lottery.Application-.Residences.on.E.pdf)

**Comment by duffy-james** [comment]
in drupal
