### ISSUE TITLE
8 Banton Income Restricted Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#474]
Hi James, 

Contact person: alexis buckley, alexis.buckley@boston.gov

Child of #376

We will need this by 10/15/18

We need a RENTAL application for the following:

Distribution Period: 10/1618 -10/25/18

Development name:  8 Banton Street
Development Address:  8 Banton Street, Dorchester, MA 02124
Deadline to submit the application: 11/1/18/18
Address to mail application: Maloney Properties, ℅ Banton Lottery, 27 Mica Lane, Wellesley, MA 02481

Developer:  Connelly Construction
Email:  connellymanagement@verizon.net
Telephone 617-436-3047

Agent: Maloney Properties, Inc.
Email: jcostello@maloneyproperties.com
Telephone: 781-992-5308

Section 2: 

- [ ] Remove all but 2 Bedroom units
- [ ] Remove question about Vision Impairment
- [ ] Remove question about Deaf/hard of hearing
- [ ] Remove 1 bedroom from the mobility impairment unit type.

Section 4: 

- [ ] Remove  all but Boston Residency

I have also attached the paper application. 
We will need the application by 10/15/18

Please also share the spreadsheet with mjanicki@maloneyproperties.com, jcostello@maloneyproperties.com , alexis.buckley@boston.com (all in view only) 

Thank you,

[Standardized Lottery Application 8 Banton St. CM.pdf](https://github.com/CityOfBoston/Forms/files/2466674/Standardized.Lottery.Application.8.Banton.St.CM.pdf)

**Comment by duffy-james** [comment]
in drupal
