### ISSUE TITLE
Goddard House Income Restricted Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#476]
Hi James, 

Contact person: alexis buckley, alexis.buckley@boston.gov

Child of #376

We will need this by 10/17/18

We need a rental  application for the following:

Distribution Period: 10/18/18 - 10/29/18

Development name: Goddard House Redevelopment
Development Address: 201-221 South Huntington Avenue, Jamaica Plain MA 02130
Deadline to submit the application: 11/6/18
Address to mail application:  SEB, 257 Hillside Avenue, Needham, MA 02494

Developer: Geoff Kahi
Email: gkahi@samuelsre.com
Telephone: 617-603-5417

Agent: Brian Engler
Email: brian@s-e-b.com
Telephone: 617-782-2300 x203

Section 2:
Please REMOVE 
- [ ]  Micro,
- [ ]  3 bedrooms
- [ ]  4 bedrooms
- [ ]  5 bedrooms, and 
- [ ] 6 bedrooms

Please REMOVE
- [ ] 1 bedroom mobility impairment
- [ ] 2 bedroom deaf/hard of hearing
- [ ] All vision impairment.

Please ADD
- [ ] studio Deaf/Hard of Hearing

Section 4:

- [ ] Please REMOVE  everything but Boston Resident

I have also attached the paper application. (ATTACH PAPER APPLICATION)

We will need the application by 10/17/18

Please also share (view only) the spreadsheet with info@sebhousing.com and alexis.buckley@boston.gov  

Thank you,

[Goddard House Income Restricted  Housing Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/2468894/Goddard.House.Income.Restricted.Housing.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal

**Comment by duffy-james** [comment]
in Drupal
