### ISSUE TITLE
1943 Dorchester Avenue Income-Restricted Rental Housing Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#479]
Hi James, 

Contact person: alexis.buckley@boston.gov

Child of #376

We will need this by 11/25/18

We need a RENTAL application for the following:

Distribution Period: 11/26/18 - 12/10/18

Development name: 1943 Dot Ave 
Development Address: 1943 Dorchester Ave, Dorchester, MA 02124
Deadline to submit the application:12/10/18
Address to mail application:

Developer: Jordan Stone  
Email: jmstone@peregrinegrp.com 
Telephone: 401-270-0660

Agent: Nicola Francis
Email: Nicola@Lenoxproperty.com
Telephone: 617-447-9312

Please Remove: All bedroom options EXCEPT

- [ ] Studio,
- [ ] 1 bedroom, and 
- [ ] 2 bedroom 

- [ ] Please remove all disabilities questions

- [ ] Please remove all preference information EXCEPT Boston residency

I have also attached the paper application.

We will need the application by DATE 11/25/18

Please also share the spreadsheet in view only with alexis.buckley@boston.gov Nicola@Lenoxproperty.com

Thank you,

[1943 DOT Standardized Lottery Application Template 4.0-2.pdf](https://github.com/CityOfBoston/Forms/files/2501912/1943.DOT.Standardized.Lottery.Application.Template.4.0-2.pdf)

**Comment by duffy-james** [comment]
in Drupal
