### ISSUE TITLE
410 West Broadway Home  Ownership Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#480]
Hi James, 

Contact person: alexis, alexis.buckley@boston.gov

Child of #376

We will need this by ASAP

We need a Sales  application for the following:

Distribution Period: 11/12/18 - 11/22/18

Development name:  410 West Broadway
Development Address:  410 West Broadway, South Boston, 02127
Deadline to submit the application: 11/29/18
Address to mail application:  Patrick Foley, 308 Victory Road, Quincy, MA 02169

Developer:  Walter Huntington LLC
Email:  dmaguire@waterhuntington.com 
Telephone 401-533-7199

Agent: Patric Foley
Email: attorneypatrickjfoley@gmail.com 
Telephone: 617-653-1746

Section 2: 

Please REMOVE :
- [ ] All except 2 Bedroom

 
Please REMOVE:
- [ ] All disability questions

Section 3: 
Please REMOVE
- [ ] all references to housing assistance

Section 4:
Please REMOVE
All preferences except: 

- [ ] First Time Home buyer
- [ ] Boston Residency Preference

I have also attached the paper application. 

We will need the application by ASAP

Please also share the spreadsheet (view only) with alexis.buckley@boston.gov and attorneypatricjfoley@gmail.com 

Thank you

[410 West Broadway Standardized Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/2567144/410.West.Broadway.Standardized.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in Drupal
