### ISSUE TITLE
206 West Broadway Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#481]
Hi James, 

Contact person: alexis.buckley@boston.gov

Child of #376

We will need this by 11/30/18

We need a Rental application for the following:

Distribution Period: 12/1/18 - 12/10/18

Development name: 206 West Broadway
Development Address:  206 West Broadway, South Boston, MA 02127
Deadline to submit the application: December 17,  2018
Address to mail application: South Boston Neighborhood Deveknonabt Corporation, 273 D Street, South Boston, MA 02127

Developer: South Boston Neighborhood Development Corporation  
Email: 206westbroadway@sbndc.org
Telephone (617) 268-9610

Agent: Michelle Zenga, SBNDC
Email:  michelle.zenga@sbndc.org 
Telephone: 617-464-2483

Section 2: 

Please remove all but:
Studio
One-Bedroom 

Remove all disability  EXCEPT mobility
Please remove all but one-bedroom for mobility 

Section 4: 
Please remove all preferences EXCEPT
Boston Residency

I have also attached the paper application. 

We will need the application by end of day tomorrow

Please also share the spreadsheet in view only with alexis.buckley@boston.gov, michelle.zenga@sbndc.org , and cheryl.conley@sbndc.org 

Thank you

[206 West Broadway Rental Housing Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/2629888/206.West.Broadway.Rental.Housing.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in Drupal
