### ISSUE TITLE
630 Washington Street Income Restricted Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#482]
Hi James, 

Contact person: alexis.buckley@boston.gov

Child of #376

We will need this by 12/4/18

We need a Rental application for the following:

Distribution Period: 12/5/18 - 12/14/18

Development name: Liberty Tree Lofts 
Development Address:  630 Washington Street
Deadline to submit the application: December 21,  2018
Address to mail application: Maloney Properties, Inc. ATTENTION LIBERTY TREE LOFTS LOTTERY, 27 Mica Lane, Wellesley, MA 02481

Developer: William J Thibeault and James Powell
Email: tuppenney@comcast.net, jpowell.thibeaultproperties@gmail.com 
Telephone (617) 387-3700

Agent: John Costello, Maloney Properties
Email: jcostello@maloneyproperties.com 
Telephone: 617-209-5250

Section 2: 

- [ ] Please remove all but Studio

- [ ] Remove all disability  EXCEPT mobility
- [ ] Please remove all and ADD studio under mobility 

Section 4: 

- [ ] Please remove all preferences EXCEPT Boston Residency

I have also attached the paper application. 

We will need the application by end of day Tuesday, 12/4/18

Please also share the spreadsheet in view only with alexis.buckley@boston.gov, jcostello@maloneypropertis.com dlin@maloneyproperties.com 

Thank you,

[630 Washington Street Rental Housing Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/2630387/630.Washington.Street.Rental.Housing.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
