### ISSUE TITLE
480 Rutherford Ave Income Restricted Rental Housing Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#483]
Hi James, 

Contact person: alexis.buckley@boston.gov

Child of #376

We will need this by 12/4/18

We need a Rental application for the following:

Distribution Period: 12/5/18 - 12/14/18

Development name: 480 Rutherford
Development Address:  480 Rutherford
Deadline to submit the application: December 21,  2018
Address to mail application: Maloney Properties, Inc. ATTENTION 480 RUTHERFORD LOTTERY, 27 Mica Lane, Wellesley, MA 02481

Developer: Chris Kaneb, Hood Park LLC
Email: ckaneb@catamountmanagement.com 
Telephone (617) 331-4281

Agent: John Costello, Maloney Properties
Email: jcostello@maloneyproperties.com 
Telephone: 617-209-5250

Section 2: 

Please remove all but:
- [ ] Studio
- [ ] One-Bedroom
- [ ] Two Bedroom

- [ ] Remove Vision Impairment

- [ ] Please remove one-bedroom mobility
- [ ] Please remove two-bedroom deaf/hard of hearing
- [ ] Please add studio deaf/hard of hearing

Section 4: 
Please remove all preferences EXCEPT
- [ ] Boston Residency

I have also attached the paper application. 

We will need the application by end of day Tuesday, 12/4/18

Please also share the spreadsheet in view only with alexis.buckley@boston.gov, jcostello@maloneypropertis.com dlin@maloneyproperties.com 

Thank you,

[480 Rutherford Rental Housing Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/2630867/480.Rutherford.Rental.Housing.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in Drupal
