### ISSUE TITLE
214 Market Street Income Restricted Home Ownership Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#484]
Hi James, 

Contact person: alexis.buckley@boston.gov

Child of #376

We will need this by 12/4/18

We need a Sales application for the following:

Distribution Period: 12/5/18 - 12/14/18

Development name: 214 Market St. 
Development Address:  224 Market Street, 
Deadline to submit the application: December 21,  2018
Address to mail application: Maloney Properties, Inc. ATTENTION 214 MARKET STREET LOTTERY, 27 Mica Lane, Wellesley, MA 02481

Developer: Jacob Simmons, City Realty Group
Email: jacob.simmons@cityrealtyboston.com 
Telephone 857-207-1664

Agent: John Costello, Maloney Properties
Email: MarketStreet@maloneyproperties.com 
Telephone: 781-992-5309

Section 2: 

Please REMOVE: 

- [ ] 1. Studio
- [ ] 2. 4-Bedroom
- [ ] 3. 5-Bedroom
- [ ] 4. 6-Bedroom

- [ ] Remove all disability questions

Section 3: 

- [ ] Please REMOVE all Housing Assistance Questions

Section 4: 
Please remove all preferences EXCEPT:

- [ ] Boston Residency
- [ ] First Time Home Buyer

I have also attached the paper application. 

We will need the application by end of day Tuesday, 12/4/18

Please also share the spreadsheet in view only with alexis.buckley@boston.gov, jcostello@maloneypropertis.com dlin@maloneyproperties.com 

Thank you,

[214 Market Street Home Ownership Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/2631172/214.Market.Street.Home.Ownership.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
