### ISSUE TITLE
Madison Melnea Cass Apartments Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#485]
Hi James, 

Contact person: alexis.buckley@boston.gov 

Child of #376

We will need this by Monday, 1/14/19

We need a rental  application for the following:

Distribution Period: 1/14/19 - 2/13/19

Development name:  Madison Melnea Cass Apartments
Development Address:  40 Raynor Circle + 600 Melnea Cass Blvd., Roxbury, MA 02120
Deadline to submit the application: 2/13/19
Address to mail application: WinnResidential Management Office, 122 Dewitt Drive, Roxbury MA 02120 

Developer:  Jeanne Pinado, Madison Park Development Corporation
Email:  JPinado@madison-park.org 
Telephone 617-541-3900

Agent: Genesa Patten, Winn Residential
Email:madisonmelnea@gmail.com 
Telephone: 617-445-8338

Section 2: 

Please REMOVE :

- [ ] Studio
- [ ] 4 bedroom, 
- [ ] 5 bedroom,
- [ ] 6 bedroom

 
Please REMOVE:

- [ ] Vision Impairments, and 
- [ ] Deaf/ hard of hearing.  

Please ADD:

- [ ] Mobility Impairment 3 Bedroom

Section 4:
Please REMOVE

- [ ] All preferences but Boston Residency Preference

I have also attached the paper application. (ATTACH PAPER APPLICATION)

We will need the application by 1/14/19

Please also share the spreadsheet (view only) with alexis.buckley@boston.gov, stranstamar@madison-park.org and madisonmelnea@gmail.com 

Thank you,

[Madison Park Melnea Cass Apartments Rental Housing Lottery Application .pdf](https://github.com/CityOfBoston/Forms/files/2742771/Madison.Park.Melnea.Cass.Apartments.Rental.Housing.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in Drupal
