### ISSUE TITLE
JP PItts Portfolio Affordable Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#486]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by today (SORRY)

We need a RENTAL application for the following:

Distribution Period: 2/11/19 - 3/11/19

Development name:  LPI Pitts Portfolio 
Development Address:  Multiple addresses in Roxbury and Dorchester, MA

Deadline to submit the application: 3/13/19
Address to mail application:Peabody Properties, Inc., ℅ LPI Pitts Portfolio Waitlist Lottery, 536 Granite Avenue, Braintree, MA 02184

Developer:  Teronda Ellis, Jamaica Plain Neighborhood Development Corporations (JPNDC) 
Email:  telllis@jpndc.org 
Telephone 617-522-2424 x260 

Agent: Tamme Polson, Peabody Properties 
Email: tpolson@peabodyproperties.com
Telephone: 781-794-1032

Section 2:
- [ ] Please REMOVE  Studio 

Please KEEP:
- [ ] 1 bedroom Mobility
- [ ] 2 bedroom Mobility

Please ADD:
- [ ]  3 bedroom Mobility
- [ ]  6 bedrooms to Mobility 

Please KEEP: 
- [ ] 1 bedroom Vision
- [ ] 2 bedroom Vision

Please ADD: 
- [ ] 4 bedroom Vision

Please KEEP:
- [ ] 1 bedroom Deaf
- [ ] 2 bedroom Deaf

Please ADD: 
- [ ] 4 bedroom Deaf

Please ADD:
- [ ] Up to 12 household members

Section 4
Please REMOVE all EXCEPT:
- [ ] Boston Residency Preference

I have also attached the paper application.

We will need the application by end of day Today (again, very sorry)

Please also share the spreadsheet with tammepolson@gmail.com jcastro@peabodyproperties.com, alexis.buckley@boston.gov, affirmativemarketing@boston.gov 

Thanks, James!

[JP Pitts Portfolio Standardized Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/2851359/JP.Pitts.Portfolio.Standardized.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in Drupal
