### ISSUE TITLE
5 McBride Income Restricted Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#487]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by 2/27/19

We need a RENTAL application for the following:

Distribution Period: 2/28/19 - 3/9/19

Development name:  5 McBride Street
Development Address:  5 McBride Street, Jamaica Plain, MA 02130
Deadline to submit the application: 3/11/19
Address to mail application: William Raveis Real Estate, Attention Michael Dorion, 16 Clarendon Street, Boston, MA 02116

Developer: TGJP, LLC
Email:  steve@ballasgroup.com
Telephone: 617-977-4913

Agent: The Residential Group at WIlliam Raveis
Email: michael.dorion@raveis.com 
Telephone: 617-470-4930 

Section 2: 

- [ ] Please REMOVE all EXCEPT 2 bedroom
- [ ] Please REMOVE all references to units built out for persons with disabilities

Section 4:

- [ ] Please REMOVE all EXCEPT Boston Residency Preference

I have also attached the paper application. 

We will need the application by 2/27/19

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov , telicia.flucas@raveis.com, michaelfdorion@gmail.com, katiegrealish33@gmail.com 

Thank you,

[5 McBride Standardized Housing Lottery Application (1).pdf](https://github.com/CityOfBoston/Forms/files/2852646/5.McBride.Standardized.Housing.Lottery.Application.1.pdf)

**Comment by duffy-james** [comment]
in Drupal
