### ISSUE TITLE
933 East 2nd Street Income Restricted Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#488]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by 4/1/19

We need a RENTAL application for the following:

Distribution Period: 4/4/19 - 4/13/19

Development name:  933 East Second Street
Development Address:  933 East Second Street, South Boston, MA 02127
Deadline to submit the application: 4/15/19
Address to mail application: THUMBPRINT REALTY, 472A Washington Street, Dorchester, MA 02124

Developer: Sing Ming Chan
Email:  singmchan@gmail.com
Telephone:860-985-0379

Agent: David Adams
Email: Adamsjr2017@gmail.com
Telephone: 857-237-4226

Section 2: 
Please REMOVE
- [ ] ALL except 2 bedroom units

Please REMOVE:
- [ ] All Deaf/hard of hearing
- [ ] All Vision Impairment

Please REMOVE:
- [ ] The 1 bedroom option in mobility impairment

Section 4:
Please REMOVE
- [ ] All except Boston Residency Preference

I have also attached the paper application. 

We will need the application by 4/1/19

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov, Adamsjr2017@gmail.com, inderaram@gmail.com 

Thank you!

[933 East 2nd Street Standardized Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/2927807/933.East.2nd.Street.Standardized.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in Drupal
