### ISSUE TITLE
Lucky Strike Income Restricted Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#489]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov 
Child of #376

We will need this by Friday April 5, 2019

We need a RENTAL application for the following:

Distribution Period: April 8 - April 19, 2019

Development name: Lucky Strike Residency
Development Address: 281 Adams Street, Dorchester, MA 02122
Deadline to submit the application: April 21, 2019
Address to mail application:

Developer: Hiep Chu
Email: hiepchu@btcompanies.net 

Agent: Same as above
Email: rental@btcompanies.net
Telephone:  617-637-3538

Section 2:

- [ ] Please KEEP ONLY  Studios, 1-bedrooms, and 2-bedrooms
- [ ] Please REMOVE all disabilities questions.

Section 4:

- [ ] Please REMOVE all preferences EXCEPT Boston Residency

We will need the application by Friday April 5, 2019

Please also share the spreadsheet with rental@btcompanies.net, hiepchu@btcompanies.net,  thuy@btcompanies.net, alexis.buckley@boston.gov and affirmativemarketing@boston.gov 

I have attached a copy of the PDF application here as well.

Thanks you!

[Lucky Strike Standardized Housing Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/3030714/Lucky.Strike.Standardized.Housing.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
