### ISSUE TITLE
735 Truman Parkway Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#490]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov 
Child of #376

We will need this by Friday April 5, 2019

We need a RENTAL application for the following:

Distribution Period: April 6 - April 16, 2019

Development name: 739 Truman Parkway
Development Address: 739 Truman Parkway, Hyde Park, MA 02136
Deadline to submit the application: April 23, 2019
Address to mail application: Maloney Properties, Inc., Attention: Truman Parkway Lottery, 27 Mica Lane, Wellesley MA 02481

Developer: Todd Nordblom, 
Email: TNordblom@nordblom.com 

Agent: Maloney Properties, Inc.
Email: jcostello@maloneyproperties.com 
Telephone:  617-209-5250

Section 2:

- [ ] Please KEEP ONLY  Studios, 1-bedrooms, and 2-bedrooms
- [ ] Please REMOVE vision impairment
- [ ] Please REMOVE 2 bedroom option in the mobility
- [ ] Please REMOVE 2 bedroom option in the deaf/hard of hearing.

Section 4:

- [ ] Please REMOVE all preferences EXCEPT Boston Residency

We will need the application by Friday April 5, 2019

Please also share the spreadsheet with jcostello@maloneyproperties.com; dlin@maloneyproperties.com; ddanieli@maloneyproperties.com ; mdeandrade@maloneyproperties.com, alexis.buckley@boston.gov and affirmativemarketing@boston.gov 

Thank you!!

[735 Truman Parkway Standardized Lottery Application (1).pdf](https://github.com/CityOfBoston/Forms/files/3031284/735.Truman.Parkway.Standardized.Lottery.Application.1.pdf)

**Comment by duffy-james** [comment]
in Drupal
