### ISSUE TITLE
40 Malvern Street Income-restricted Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#494]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by 2/27/19

We need a RENTAL application for the following:

Distribution Period: 5/13/19 - 5/22/19

Development name:  40 Malvern Street
Development Address:  40 Malvern Street, Allston, MA 02135
Deadline to submit the application: 5/29/19
Address to mail application: Maloney Properties, Inc. Attention 40 Malvern Lottery, 27 Mica Lane, Wellesley, MA 02481

Developer: Jameson Brown, The Hamilton Company
Email:  jbrown@TheHamiltonCompany.com 
Telephone 617-783-0039

Agent: John Costello, Maloney Properties, Inc.
Email: jcostello@maloneypropoerties.com 
Telephone: 617-209-5250

Section 2: 
Please REMOVE:
- [ ] Micro
- [ ] Studio
- [ ] 3 bedroom
- [ ] 4 bedroom
- [ ] 5 bedroom
- [ ] 6 bedroom

Please REMOVE
- [ ] All Vision Impairment
- [ ] 2 bedroom Mobility
- [ ] 2 bedroom Deaf/hard of hearing

Section 4:
- [ ] Please REMOVE ALL Except Boston Residency

I have also attached the paper application. 

We will need the application by 5/13/19

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov , Doris Lin <dlin@maloneyproperties.com>; Diandra Danieli <ddanieli@maloneyproperties.com>; Mbom DeAndrade <mdeandrade@maloneyproperties.com>; John Costello <jcostello@maloneyproperties.com>

Thank you,

[40 Malvern Standardized Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/3170507/40.Malvern.Standardized.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
