### ISSUE TITLE
150 Camden Income-restricted Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#496]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by 5/13/19

We need a RENTAL application for the following:

Distribution Period: 5/13/19 - 5/22/19

Development name:  150 Camden
Development Address:  150 Camden Street, Roxbury, MA 02119
Deadline to submit the application: May 29, 2019
Address to mail application: Maloney Properties, Inc. Attention 150 CamdenLottery, 27 Mica Lane, Wellesley, MA 02481

Developer: Jameson Brown, The Hamilton Company
Email:  jbrown@TheHamiltonCompany.com  
Telephone 617-783-0039

Agent: John Costello, Maloney Properties, Inc.
Email: jcostello@maloneypropoerties.com  
Telephone: 617-209-5250

Section 2: 
Please REMOVE:
- [ ] Micro
- [ ] Studio
- [ ] 4 bedroom
- [ ] 5 bedroom
- [ ] 6 bedroom

Please REMOVE: 
- [ ] All vision impairment
- [ ] All deaf/hard of hearing
- [ ] 1 bedroom Mobility

Section 4:
- [ ] Please REMOVE all except Boston Resident

I have also attached the paper application. 

We will need the application by today (sorry). 

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov , Doris Lin <dlin@maloneyproperties.com>; Diandra Danieli <ddanieli@maloneyproperties.com>; Mbom DeAndrade <mdeandrade@maloneyproperties.com>; John Costello <jcostello@maloneyproperties.com>

THANK YOU!

[150 Camden Standardized Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/3170536/150.Camden.Standardized.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
