### ISSUE TITLE
Melnea Residences Online Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#497]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by 6/3/19

We need a RENTAL application for the following:

Distribution Period: 6/3/19 - 6/12/19

Development name:  The Melnea Apartments
Development Address:  431 Melnea Cass Apartments
Deadline to submit the application: June 19, 2019
Address to mail application: Maloney Properties, Inc., Attention: Melnea Cass Lottery, 27 Mica Lane, Wellesley MA 02481

Developer: Kamran Zahedi, Urbanica Boston
Email:  kzahedi@urbanicaboston.com 
Telephone 617-654-8900

Agent: John Costello, Maloney Properties, Inc. 
Email: jcostello@maloneyproperties.com 
Telephone: 617-209-5250

Section 2: 
Please REMOVE 
- [ ] Micro
- [ ] 3 bedroom
- [ ] 4 bedroom
- [ ] 5 bedroom
- [ ] 6 bedroom

Please REMOVE
- [ ] All Vision Impairment options
- [ ] All Deaf/Hard of Hearing options
- [ ] 2 bedroom Mobility option

Section 4:
- [ ] Please REMOVE the following preferences:
- [ ] Urban Renewal
- [ ] Artists
- [ ] Senior
- [ ] First-Time-Home-Buyer

Please ADD: 

- [ ] “Do you qualify for the Neighborhood Diversity Preservation Preference Pilot?”
- [ ] After the Boston Residency preference footnote, please ADD:  “** The goal of the Diversity Preservation Preference Pilot policy is to stabilize neighborhoods and minimize displacement by providing a preference for existing neighborhood residents for up to 50% of the units in projects located in non-segregated geographies with high rates of displacement or households at high risk of displacement. If you live within a quarter mile of this development, you may qualify. To see a map and a listing of qualifying street addresses please see www.TheMelnealottery.com or contact the agent listed above.”

I have also attached the paper application. 
We will need the application by 6/3/19

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov, jcostello@maloneyproperties.com, dlin@maloneyproperties.com, ddanieli@maloneyproperties.com  mdeandrade@maloneyproperties.com 

Thank you,

[Melnea Residences Standardized Lottery Application (1).pdf](https://github.com/CityOfBoston/Forms/files/3241787/Melnea.Residences.Standardized.Lottery.Application.1.pdf)

**Comment by duffy-james** [comment]
in drupal
