### ISSUE TITLE
54 Pleasant Housing Lottery Online Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#498]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by 6/10/19

We need a RENTAL application for the following:

Distribution Period: 6/10/19 -6/19/19

Development name:  54 Pleasant Street
Development Address:  54 Pleasant Street, Dorchester, MA 02125
Deadline to submit the application: 6/25/19
Address to mail application: Maloney Properties, Inc., Attention: 54 Pleasant Street Lottery, 27 Mica Lane, Wellesley MA 02481

Developer: Joey Arcari
Email:  joey@taverninthesquare.com 
Telephone 617-320-7553

Agent: John Costello
Email: jcostello@maloneyproperties.com 
Telephone: 617-209-5250

Section 2: 
- [ ] Please REMOVE all EXCEPT 2-bedrooms
- [ ] Please REMOVE all disability questions

Section 3: 
- [ ] Please REMOVE the two housing assistance questions

Section 4:
Please REMOVE the following preference questions: 
- [ ] Homelessness
- [ ] Artist
- [ ] 62 years old

I have also attached the paper application.

We will need the application by Monday, June 10, 2019

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov, jcostello@maloneyproperties.com, dlin@maloneyproperties.com, ddanieli@maloneyproperties.com, mdeandrade@maloneyproperties.com 

Thank you,

[54 Pleasant Lottery Application (1).pdf](https://github.com/CityOfBoston/Forms/files/3263080/54.Pleasant.Lottery.Application.1.pdf)

**Comment by duffy-james** [comment]
in drupal
