### ISSUE TITLE
45 Burnett Home Ownership Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#499]
“Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov

Child of #376

We will need this by Monday, 6/10/19

We need a SALE application for the following:

Distribution Period: Monday, June 10, 2019 - Wednesday, June 19, 2019

Development name: 45 Burnett
Development Address: 45 Burnett St, Jamaica Plain, MA 02130 
Deadline to submit the application: 6/26/19 (This is correct. It’s a day later than 54 Pleasant)

Address to mail application: Maloney Properties, Inc. Attention: 45 Burnett Lottery
27 Mica Lane, Wellesley MA 02481

Developer: Tim McGovern, New Boston Ventures
Email: tmcgovern@newbostonventures.com 
Telephone: 617-834-9486

Agent: John Costello
Email: jcostello@maloneyproperties.com 
Telephone: 617-209-5250

Section 2:
Please REMOVE
- [ ] Micro
- [ ] Studio
- [ ] 4 bedroom
- [ ] 5 bedroom
- [ ] 6 bedroom
- [ ] Please REMOVE all disability questions

Section 3: 
- [ ] Please REMOVE the two housing assistance questions

Section 4:
Please REMOVE the following preference questions: 
- [ ] Homelessness
- [ ] Artist
- [ ] 62 years old

I have also attached the paper application.

We will need the application by Monday, June 10, 2019

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov, jcostello@maloneyproperties.com, dlin@maloneyproperties.com, ddanieli@maloneyproperties.com, mdeandrade@maloneyproperties.com 

Thank you,

[45 Burnnett Lottery Application .pdf](https://github.com/CityOfBoston/Forms/files/3263260/45.Burnnett.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
