### ISSUE TITLE
A.O. Flats Rental Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#500]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by end of the day, Thursday, June 13, 2019

We need a RENTAL application for the following:

Distribution Period: Friday, June 14, 2019, to Monday, July 15, 2019

Development name:  A.O. Flats at Forest Hills
Development Address:  95 Hyde Park Avenue, Boston, MA 02130
Deadline to submit the application: July 15, 2019 
Address to mail application: Woodbourne Apartments, Attn: Leasing Office, 6 Southbourne Road, Jamaica Plain, MA 02130

Developer: Eliza Datta.
Email:  edatta@tcbinc.org
Telephone: 617-695-9595 

Agent: Linda Dalrymple
Email: linda.dalrymple@TCBINC.ORG
Telephone:  914-484-1582

Section 2: 
Please REMOVE:
- [ ] Micro
- [ ] 4 bedroom
- [ ] 5 bedroom
- [ ] 6 bedroom

- [ ] Please ADD 3 bedroom Mobility
- [ ] Please REMOVE 1 bedroom deaf/hard of hearing
- [ ] Please REMOVE 1 bedroom vision impairment
- [ ] Please ADD 3 bedroom deaf/hard of hearing
- [ ] Please ADD 3 bedroom vision impairment

Section 4:
- [ ] Please REMOVE all EXCEPT Boston Residency Preference

I have also attached the paper application. 

We will need the application by the end of the day, June 13, 2019

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov, linda.dalrymple@tcbinc.org, steve.lodi@tcbinc.org; Lydia.scott@tcbinc.org; dbutler@tcbinc.org

Thank you,

[A.O. Flats at Forest Hills Lottery Application .pdf](https://github.com/CityOfBoston/Forms/files/3281364/A.O.Flats.at.Forest.Hills.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
