### ISSUE TITLE
20 Taft Hill Income-restricted Home Ownership Lottery Application 

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#501]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by Thursday, June 13, 2019

We need a Home Ownership application for the following:

Distribution Period: Monday, June 24, 2019 – Wednesday, July 3, 2019

Development name: 20 Taft Hill Park 
Development Address:  20 Taft Hill Park, Boston, MA 02131
Deadline to submit the application: July 10, 2019
Address to mail application: Maloney Properties, Inc., Attn: Taft Hill Park, 27 Mica Lane, Wellesley, MA 02481

Developer: Paul Quinn
Email:  paul@gpqmaintenance.com
Telephone: 617-719-1644 

Agent: John Costello
Email: jcostello@maloneyproperties.com
Telephone: 617-209-5250

Section 2: 
Please **REMOVE** everything **EXCEPT** 
- [ ] 1 bedroom
- [ ] 2 bedroom

- [ ] Please REMOVE ADA Section

Section 3: 
- [ ] Please REMOVE the two Housing Assistance Questions

Section 4:
Please **REMOVE** everything **EXCEPT** the
- [ ] First Time Home Buyer
- [ ] Boston Residency Preferences

I have also attached the paper application. 

We will need the application by June 24, 2019

Please also share the spreadsheet in view only with alexis.buckley@boston.gov, affirmativemarketing@boston.gov , jcostello@maloneyproperties.com; dlin@maloneyproperties.com; ddanieli@maloneyproperties.com; mdeandrade@maloneyproperties.com

Thank you,

[20 Taft Hill Park Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/3311821/20.Taft.Hill.Park.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
