### ISSUE TITLE
350 Bremen Rental Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#502]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by 2/26/19

We need a RENTAL application for the following:

Distribution Period: 6/27/19 - 7/8/29

Development name: 350 Bremen Street
Development Address:  348-350 Bremen Street, East Boston, MA 02128
Deadline to submit the application: 7/29/19
Address to mail application: LAR Properties, Inc., ℅ 350 Bremen Lottery, 282 Bennington Street, East Boston, MA 02128

Developer: LAR Properties, Celeste Ribeiro Myers
Email:  celeste@spinellis.com 
Telephone 617-567-1992 x817

Section 2: 
- [ ] Please REMOVE all EXCEPT 2 bedroom
- [ ] Please REMOVE all disability questions

Section 4:
- [ ] Please REMOVE all EXCEPT Boston Residency Preference

I have also attached the paper application. 

We will need the application by 6/26/19

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov, celeste@spinellis.com 

Thank you!

[350 Bremen Street Standardized Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/3316237/350.Bremen.Street.Standardized.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
