### ISSUE TITLE
General Heath Square/61 Heath Rental Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#503]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by 2/27/19

We need a RENTAL application for the following:

Distribution Period: 6/28/19

Development name:  General Heath Square- 61 Heath
Development Address:  61 Heath Street, Jamaica Plain, MM 02130
Deadline to submit the application: 7/29/19
Address to mail application: Peabody Properties, Inc., ℅ 61 Heath Lottery, 536 Granite Street, Braintree, MA 02184

Developer: JPNDC, Richard Thal
Email:  rthal@jpndc.org 
Telephone 617-522-2424

Agent: Tamme Polson, Peabody Properties
Email: tpolson@peabodyproperties.com 
Telephone: 781-794-1032

Section 2: 
Please REMOVE: 
- [ ] Micro
- [ ] Studio
- [ ] 4 bedroom
- [ ] 5 bedroom
- [ ] 6 bedroom

- [ ] Please ADD 3 bedroom mobility
- [ ] Please REMOVE vision impairments

Section 4:
- [ ] Please REMOVE all EXCEPT Boston Residency Preference

I have also attached the paper application. 

We will need the application by 6/27/19

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov, Tpolson@peabodyproperties.com, Cmarrocco@peabodyproperties.com, Dlablanc@peabodyproperties.com, Jjerdon@peabodyproperties.com, kpage@peabodyproperties.com 

Thank you,

[General Heath Square Apartments Standardized Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/3316261/General.Heath.Square.Apartments.Standardized.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
