### ISSUE TITLE
Clarion Rental Housing Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#504]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by 2/27/19

We need a RENTAL application for the following:

Distribution Period: 6/28/19 -7/29/19

Development name:  The Clarion
Development Address:  311 Blue Hill Avenue, Dorchester, MA 02121
Deadline to submit the application: 7/29/19
Address to mail application: Franklin Park Apartments, Leasing Office, 132 Seaver Street, Boston MA 02121

Developer: Andrew Waxman, The Community Builders, Inc.
Email:  andrew.waxman@tcbinc.org 
Telephone: 857-221-8643

Agent: Waldina Bonilla
Email: waldina.bonilla@TCBINC.org 
Telephone: 617-433-9755

Section 2: 
Please REMOVE: 
- [ ] Micro
- [ ] Studio
- [ ] 4 bedroom
- [ ] 5 bedroom
- [ ] 6 bedroom

- [ ] Please REMOVE Vision Impaired 1-bedroom
- [ ] Please REMOVE Deaf/Hard of Hearing 1-bedroom

Section 4:
- [ ] Please REMOVE all EXCEPT Boston Residency

I have also attached the paper application. 

We will need the application by 6/27/19

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov, tberthod@tcbinc.org, Sheila.kennerly@tcbinc.org, waldina.bonilla@tcbinc.org karim.amaro@tcbinc.org, anunez@tcbinc.org david.sanchez@tcbinc.org, linda.dalrymple@tcbinc.org

Thank you!

[The Clarion Standardized Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/3316341/The.Clarion.Standardized.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
