### ISSUE TITLE
232 Old Colony Home Ownership Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#505]
Hi James,

Contact person: Alexis Buckley, alexis.buckley@boston.gov 
Child of #376

We will need this by 7/10/19
We need a SALE application
Distribution Period: 7/11/19 - 7/22/19

Development name: 232 Old Colony
Development Address: 232 Old Colony, South Boston, MA 02127
Deadline to submit the application: 7/29/19
Address to mail application: 300 A Street, Suite 101, Attention 232 Old Colony Lottery, Boston, MA 02210

Developer: Ryan Sillery, City Point Capital
Email: rsillery@citypointcapital.com 
Telephone: 1-857-496-0425

Agent: Kelly McManama, City Point Capital
Email: kmcmanama@citypointcapital.com 
Telephone: 1-857-496-0425 extension 3

Section 2:
Please REMOVE:
- [ ] Micro
- [ ] Studio
- [ ] 3 bedroom
- [ ] 4 bedroom
- [ ] 5 bedroom

- [ ] Please REMOVE all disability questions 

Section 3:
- [ ] Please REMOVE the question on housing assistance

Section 4:
- [ ] Please REMOVE all preferences EXCEPT: 
- [ ] First Time Home Buyers
- [ ] Boston Residency

We will need the application by 7/10/19

Please also share the spreadsheet in View Only with alexis.buckley@boston.gov, affirmativemarketing@boston.gov, kmcmanama@citypointcapital.com 

Thank you,

[232 Old Colony Lottery Application.pdf](https://github.com/CityOfBoston/Forms/files/3316389/232.Old.Colony.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal
