### ISSUE TITLE
545 East Third Street Home Ownership Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#506]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by 7/12/19

We need a Home Ownership application for the following:

Distribution Period: Saturday, July 13, 2019 – Monday, July 22, 2019

Development name: 545 East Third Street Condominiums
Development Address:  545 East Third Street, South Boston, MA 02127
Deadline to submit the application: July 29, 2019
Address to mail application: South Boston NDC, 273 “D” Street, South Boston, MA 02127

Developer: Scott Miller
Email:  scottmiller5@comcast.net
Telephone: 617-216-9260

Agent: Michelle Zenga, South Boston Neighborhood Development Corporation
Email: michelle.zenga@sbndc.org 
Telephone: 617-268-9610

Section 2: 
Please REMOVE:
- [ ] Micro
- [ ] Studio
- [ ] 3 Bedroom
- [ ] 4 Bedroom
- [ ] 5 Bedroom
- [ ] 6 Bedroom

- [ ] Please REMOVE ADA Section

Section 3: 
- [ ] Please REMOVE the two Housing Assistance Questions

Section 4:
Please REMOVE everything EXCEPT the
- [ ]  First Time Home Buyer
- [ ] Boston Residency Preferences

I have also attached the paper application. 

We will need the application by 7/12/19

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov cheryl.conley@sbndc.org, michelle.zenga@sbndc.org 

Thank you,

[545 East Third Street Lottery Application .pdf](https://github.com/CityOfBoston/Forms/files/3316395/545.East.Third.Street.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal; waiting on spreadsheet
