### ISSUE TITLE
360 West 2nd Home Ownership Housing Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#508]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by 7/26/19

We need a HOMEOWNER application for the following:

Distribution Period: Saturday July 27, 2019 - Monday August 5, 2019

Development name:  360 West Second Street
Development Address:  360 West Second Street South Boston, MA 02127
Deadline to submit the application: August 12, 2019 
Address to mail application:  South Boston NDC, 273 D Street, South Boston, MA 02127

Developer:Joe Taylor
Email:  andytownproperties@gmail.com
Telephone: 857-753-8512 

Agent: Michelle Zenga
Email: michelle.zenga@sbndc.org
Telephone:  617-464-2483

Section 2: 
Please REMOVE 
- [ ] Micro
- [ ] Studio
- [ ] 3 bedroom
- [ ] 4 bedroom
- [ ] 5 bedroom
- [ ] 6 bedroom

- [ ] Please Remove ADA Housing Section

Section 3:
- [ ] Please REMOVE Housing Assistance Questions

Section 4:
Please REMOVE everything EXCEPT 
- [ ] First Time Home Buyer
- [ ] Boston Residency Preference

I have also attached the paper application. 

We will need the application by 7/26/19

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov, cheryl.conley@sbndc.org, michelle.zenga@sbndc.org 

Thank you,

[360 West Second Street Standardized Lottery Application .pdf](https://github.com/CityOfBoston/Forms/files/3316401/360.West.Second.Street.Standardized.Lottery.Application.pdf)

**Comment by duffy-james** [comment]
in drupal; need to share spreadsheet
