### ISSUE TITLE
Residences at Brighton Marine Housing Lottery Application

### ISSUE THREAD

**Issue by alexisbuckley** [CityOfBoston/Forms#509]
Hi James, 

Contact person: Alexis, alexis.buckley@boston.gov

Child of #376

We will need this by 7/1/19

We need a RENTAL application for the following:

Distribution Period: 7/1/19 - 10/1/19

Development Name:  The Residences at Brighton Marine
Development Address:  1465 Commonwealth Avenue, Brighton, MA 02135
Deadline to submit the application: 10/1/19
Address to mail application: Residences at Brighton Marine, Leasing Office, 77 Warren Street, Building 2, Brighton, MA 02135

Developer: Michael Dwyer, Brighton Marine Housing Limited Partnership
Email:  michaeldwyer@brighton-marine.org 
Telephone 617-208-6231

Agent: Joe Thifault
Email: jthifault@winnco.com 
Telephone: (781) 581-2180 

Section 2: 
Please REMOVE: 
- [ ] Micro
- [ ] 4 bedroom
- [ ] 5 bedroom
- [ ] 6 bedroom

Please ADD: 
- [ ] 3 bedroom mobility
- [ ] 3 bedroom deaf/hard of hearing
- [ ] 3 bedroom vision impairments

Section 4:
- [ ] Please ADD “Are you a Veteran*?” 
- [ ] Please REMOVE All except Boston Residency (and the veteran’s)

- [ ] Please ADD “*Veteran’s Status Brighton Marine has a preference for Active Duty, Reservists, Veterans, and their families. Examples of documentation required to verify qualification for this preference include: 
- [ ] Current or past deployment orders
- [ ] Notice of discharge or letter from Veteran’s Affairs (DD-214/DD215)”

I have also attached the paper application. 

We will need the application by Monday, 7/1/19

Please also share the spreadsheet with alexis.buckley@boston.gov, affirmativemarketing@boston.gov, jhuang@winnco.com, cdebrito@winnco.com,  slee@winnco.com,  khudson@winnco.com  clau@winnco.com, ychan@winnco.com,  kpavetto@winnco.com,  lphung@winnco.com  

Thank you,
[Brighton Marine Standardized Lottery Application  (1).pdf](https://github.com/CityOfBoston/Forms/files/3334645/Brighton.Marine.Standardized.Lottery.Application.1.pdf)

**Comment by duffy-james** [comment]
in drupal
